hsfs: /hsfs/nfs3/acl3clnt.c File Reference
acl3clnt.c File Reference
#include <memory.h>
#include "acl3.h"
#include "nfs3.h"
Functions
void * aclproc3_null_3 (void *argp, CLIENT *clnt)
GETACL3res * aclproc3_getacl_3 (GETACL3args *argp, CLIENT *clnt)
SETACL3res * aclproc3_setacl_3 (SETACL3args *argp, CLIENT *clnt)
GETXATTRDIR3res * aclproc3_getxattrdir_3 (GETXATTRDIR3args *argp, CLIENT *clnt)
Function Documentation
void* aclproc3_null_3 (void * argp, CLIENT * clnt)
Definition at line 14 of file acl3clnt.c.
References ACLPROC3_NULL.
GETACL3res* aclproc3_getacl_3 (GETACL3args * argp, CLIENT * clnt)
Definition at line 29 of file acl3clnt.c.
References ACLPROC3_GETACL, xdr_GETACL3args(), and xdr_GETACL3res().
SETACL3res* aclproc3_setacl_3 (SETACL3args * argp, CLIENT * clnt)
Definition at line 44 of file acl3clnt.c.
References ACLPROC3_SETACL, xdr_SETACL3args(), and xdr_SETACL3res().
GETXATTRDIR3res* aclproc3_getxattrdir_3 (GETXATTRDIR3args * argp, CLIENT * clnt)
Definition at line 59 of file acl3clnt.c.
References ACLPROC3_GETXATTRDIR, xdr_GETXATTRDIR3args(), and xdr_GETXATTRDIR3res().