hsfs: /hsfs/include/hsfs.h File Reference
hsfs.h File Reference
#include <fuse/fuse_lowlevel.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include "nfs3.h"
#include "log.h"
Data Structures
struct hsfs_inode
struct hsfs_table
struct hsfs_super
struct hsfs_rw_info
struct hsfs_sattr
struct hsfs_readdir_ctx
Macros
#define FUSE_USE_VERSION 26
#define HSFS_TYPE "hsfs"
#define S_ISSETMODE(to_set) ((to_set) & FUSE_SET_ATTR_MODE)
#define S_ISSETUID(to_set) ((to_set) & FUSE_SET_ATTR_UID)
#define S_ISSETGID(to_set) ((to_set) & FUSE_SET_ATTR_GID)
#define S_ISSETSIZE(to_set) ((to_set) & FUSE_SET_ATTR_SIZE)
#define S_ISSETATIME(to_set) ((to_set) & FUSE_SET_ATTR_ATIME)
#define S_ISSETMTIME(to_set) ((to_set) & FUSE_SET_ATTR_MTIME)
#define S_ISSETATIMENOW(to_set) ((to_set) & FUSE_SET_ATTR_ATIME_NOW)
#define S_ISSETMTIMENOW(to_set) ((to_set) & FUSE_SET_ATTR_MTIME_NOW)
#define S_SETMODE(sattr) ((sattr)->valid |= FUSE_SET_ATTR_MODE)
#define S_SETUID(sattr) ((sattr)->valid |= FUSE_SET_ATTR_UID)
#define S_SETGID(sattr) ((sattr)->valid |= FUSE_SET_ATTR_GID)
#define S_SETSIZE(sattr) ((sattr)->valid |= FUSE_SET_ATTR_SIZE)
#define S_SETATIME(sattr) ((sattr)->valid |= FUSE_SET_ATTR_ATIME)
#define S_SETATIMENOW(sattr) ((sattr)->valid |= FUSE_SET_ATTR_ATIME_NOW)
#define S_SETMTIME(sattr) ((sattr)->valid |= FUSE_SET_ATTR_MTIME)
#define S_SETMTIMENOW(sattr) ((sattr)->valid |= FUSE_SET_ATTR_MTIME_NOW)
#define HSFS_MAX_FILE_IO_SIZE (1048576U)
#define HSFS_DEF_FILE_IO_SIZE (4096U)
#define HSFS_MIN_FILE_IO_SIZE (1024U)
#define HSFS_MAX_READDIR_PAGES 8
#define HSFS_FILE_SYNC 2
#define HSFS_UNSTABLE 0
#define min(x, y) ((x) < (y) ? (x) : (y))
Functions
unsigned long hsfs_block_bits (unsigned long bsize, unsigned char *nrbitsp)
unsigned long hsfs_block_size (unsigned long bsize, unsigned char *nrbitsp)
int hsx_fuse_itable_init (struct hsfs_super *sb)
void hsx_fuse_iadd (struct hsfs_super *sb, struct hsfs_inode *hsfs_node)
struct hsfs_inode * hsx_fuse_iget (struct hsfs_super *sb, uint64_t ino)
int hsx_fuse_idel (struct hsfs_super *sb, struct hsfs_inode *hs_node)
int hsx_fuse_itable_del (struct hsfs_super *sb)
Variables
char * progname
int nomtab
int verbose
int fg
struct hsfs_sattr hsfs_sattr_t
Macro Definition Documentation
#define FUSE_USE_VERSION 26
Definition at line 6 of file hsfs.h.
#define HSFS_TYPE "hsfs"
Definition at line 17 of file hsfs.h.
Referenced by main().
#define S_ISSETMODE (to_set) ((to_set) & FUSE_SET_ATTR_MODE)
Definition at line 19 of file hsfs.h.
Referenced by hsi_nfs3_setattr().
#define S_ISSETUID (to_set) ((to_set) & FUSE_SET_ATTR_UID)
Definition at line 20 of file hsfs.h.
Referenced by hsi_nfs3_setattr().
#define S_ISSETGID (to_set) ((to_set) & FUSE_SET_ATTR_GID)
Definition at line 21 of file hsfs.h.
Referenced by hsi_nfs3_setattr().
#define S_ISSETSIZE (to_set) ((to_set) & FUSE_SET_ATTR_SIZE)
Definition at line 22 of file hsfs.h.
Referenced by hsi_nfs3_setattr().
#define S_ISSETATIME (to_set) ((to_set) & FUSE_SET_ATTR_ATIME)
Definition at line 23 of file hsfs.h.
Referenced by hsi_nfs3_setattr().
#define S_ISSETMTIME (to_set) ((to_set) & FUSE_SET_ATTR_MTIME)
Definition at line 24 of file hsfs.h.
Referenced by hsi_nfs3_setattr().
#define S_ISSETATIMENOW (to_set) ((to_set) & FUSE_SET_ATTR_ATIME_NOW)
Definition at line 25 of file hsfs.h.
Referenced by hsi_nfs3_setattr().
#define S_ISSETMTIMENOW (to_set) ((to_set) & FUSE_SET_ATTR_MTIME_NOW)
Definition at line 26 of file hsfs.h.
Referenced by hsi_nfs3_setattr().
#define S_SETMODE (sattr) ((sattr)->valid |= FUSE_SET_ATTR_MODE)
Definition at line 28 of file hsfs.h.
Referenced by hsi_nfs3_create().
#define S_SETUID (sattr) ((sattr)->valid |= FUSE_SET_ATTR_UID)
Definition at line 29 of file hsfs.h.
#define S_SETGID (sattr) ((sattr)->valid |= FUSE_SET_ATTR_GID)
Definition at line 30 of file hsfs.h.
#define S_SETSIZE (sattr) ((sattr)->valid |= FUSE_SET_ATTR_SIZE)
Definition at line 31 of file hsfs.h.
#define S_SETATIME (sattr) ((sattr)->valid |= FUSE_SET_ATTR_ATIME)
Definition at line 32 of file hsfs.h.
#define S_SETATIMENOW (sattr) ((sattr)->valid |= FUSE_SET_ATTR_ATIME_NOW)
Definition at line 33 of file hsfs.h.
#define S_SETMTIME (sattr) ((sattr)->valid |= FUSE_SET_ATTR_MTIME)
Definition at line 34 of file hsfs.h.
#define S_SETMTIMENOW (sattr) ((sattr)->valid |= FUSE_SET_ATTR_MTIME_NOW)
Definition at line 35 of file hsfs.h.
#define HSFS_MAX_FILE_IO_SIZE (1048576U)
Definition at line 49 of file hsfs.h.
Referenced by hsfs_block_size().
#define HSFS_DEF_FILE_IO_SIZE (4096U)
Definition at line 50 of file hsfs.h.
Referenced by hsfs_block_size().
#define HSFS_MIN_FILE_IO_SIZE (1024U)
Definition at line 51 of file hsfs.h.
Referenced by hsfs_block_size().
#define HSFS_MAX_READDIR_PAGES 8
Definition at line 57 of file hsfs.h.
#define HSFS_FILE_SYNC 2
Definition at line 123 of file hsfs.h.
Referenced by hsx_fuse_write().
#define HSFS_UNSTABLE 0
Definition at line 124 of file hsfs.h.
Referenced by hsx_fuse_write().
#define min (x, y) ((x) < (y) ? (x) : (y))
Definition at line 169 of file hsfs.h.
Referenced by hsx_fuse_read(), hsx_fuse_readdir(), and hsx_fuse_write().
Function Documentation
unsigned long hsfs_block_bits (unsigned long bsize, unsigned char * nrbitsp)
Definition at line 467 of file hsi_nfs3_mount.c.
Referenced by hsfs_block_size().
unsigned long hsfs_block_size (unsigned long bsize, unsigned char * nrbitsp)
Definition at line 486 of file hsi_nfs3_mount.c.
References hsfs_block_bits(), HSFS_DEF_FILE_IO_SIZE, HSFS_MAX_FILE_IO_SIZE, and HSFS_MIN_FILE_IO_SIZE.
Referenced by hsi_validate_mount_data().
int hsx_fuse_itable_init (struct hsfs_super * sb)
hsx_fuse_itable_init: initialize the Hash Table
Parameters
sb[IN],: the information of the superblock
Returns
: 0 if successfull, other values show an error
Definition at line 19 of file hsfs_fuse_table.c.
References hsfs_table::array, ERR, hsfs_super::hsfs_fuse_ht, HSFS_TABLE_SIZE, hsfs_table::size, and hsfs_table::use.
void hsx_fuse_iadd (struct hsfs_super * sb, struct hsfs_inode * hsfs_node)
hsx_fuse_iadd: set a inode into the Hash Table
Parameters
sb[IN],: the information of the superblock
hsfs_node[IN]:a pointer to an object of type hash_inode which describe the node information in memory
Returns
: void
Definition at line 96 of file hsfs_fuse_table.c.
References hsfs_table::array, DEBUG, hsfs_super::hsfs_fuse_ht, hsfs_inode::ino, hsfs_inode::next, and hsfs_table::use.
Referenced by hsi_nfs3_ifind().
struct hsfs_inode* hsx_fuse_iget (struct hsfs_super * sb, uint64_t ino) read
hsx_fuse_iget: Try to retrieve the node information
Parameters
sb[IN],: the information of the superblock
ino[IN],: the inode number
Returns
: a pointer to the object found if successfull,else NULL
Definition at line 115 of file hsfs_fuse_table.c.
References hsfs_table::array, hsfs_super::hsfs_fuse_ht, hsfs_inode::ino, hsfs_inode::next, and hsfs_inode::sb.
Referenced by hsi_nfs3_ifind(), hsx_fuse_access(), hsx_fuse_create(), hsx_fuse_forget(), hsx_fuse_getattr(), hsx_fuse_getxattr(), hsx_fuse_link(), hsx_fuse_lookup(), hsx_fuse_mkdir(), hsx_fuse_mknod(), hsx_fuse_opendir(), hsx_fuse_read(), hsx_fuse_readdir(), hsx_fuse_readlink(), hsx_fuse_rename(), hsx_fuse_rmdir(), hsx_fuse_setattr(), hsx_fuse_setxattr(), hsx_fuse_symlink(), hsx_fuse_unlink(), and hsx_fuse_write().
int hsx_fuse_idel (struct hsfs_super * sb, struct hsfs_inode * hs_node)
hsx_fuse_idel: Remove a node from the Hash Table
Parameters
sb[IN],: the information of the superblock
hsfs_node[IN]:a pointer to an object of type hash_inode which describe the node information in memory
Returns
: 0 if successfull, other values show an error
Definition at line 178 of file hsfs_fuse_table.c.
References hsfs_table::array, nfs_fh3::data, nfs_fh3::data_val, DEBUG, hsfs_inode::fh, hsfs_super::hsfs_fuse_ht, hsfs_inode::ino, hsfs_inode::next, and hsfs_table::use.
Referenced by hsx_fuse_forget(), and hsx_fuse_unmount().
int hsx_fuse_itable_del (struct hsfs_super * sb)
hsx_fuse_itable_del: Remove and free all member from the hashtable
Parameters
sb[IN],: the information of the superblock
Returns
: 0 if successfull, other values show an error
Definition at line 212 of file hsfs_fuse_table.c.
References hsfs_table::array, nfs_fh3::data, nfs_fh3::data_val, hsfs_inode::fh, hsfs_super::hsfs_fuse_ht, hsfs_inode::next, and hsfs_table::size.
Referenced by hsx_fuse_unmount().
Variable Documentation
char* progname
Definition at line 26 of file hsfs_main.c.
Referenced by hsi_mount_usage(), hsx_fuse_link(), hsx_fuse_mknod(), hsx_fuse_mount(), hsx_fuse_opendir(), hsx_fuse_readdir(), hsx_fuse_readlink(), hsx_fuse_symlink(), and main().
int nomtab
Definition at line 28 of file hsfs_main.c.
int verbose
Definition at line 27 of file hsfs_main.c.
int fg
Definition at line 29 of file hsfs_main.c.
Referenced by hsx_fuse_mount().
struct hsfs_sattr hsfs_sattr_t