hsfs: /hsfs/include/hsi_nfs3.h File Reference
hsi_nfs3.h File Reference
#include "hsfs.h"
#include "acl3.h"
#include "acl.h"
Functions
int hsi_nfs3_mkdir (struct hsfs_inode *parent, struct hsfs_inode **new, const char *name, mode_t mode)
int hsi_nfs3_rmdir (struct hsfs_inode *parent, const char *name)
int hsi_nfs3_unlink (struct hsfs_inode *parent, const char *name)
int hsi_nfs3_rename (struct hsfs_inode *parent, const char *name, struct hsfs_inode *newparent, const char *newname)
int hsi_nfs3_stat_to_errno (int stat)
int hsi_rpc_stat_to_errno (CLIENT *clntp)
int hsi_nfs3_readlink (struct hsfs_inode *inode, char **link)
int hsi_nfs3_symlink (struct hsfs_inode *parent, struct hsfs_inode **new, const char *link, const char *name)
int hsi_nfs3_read (struct hsfs_rw_info *rw)
int hsi_nfs3_write (struct hsfs_rw_info *rw)
int hsi_nfs3_access (struct hsfs_inode *inode, int mask)
int hsi_nfs3_create (struct hsfs_inode *parent, struct hsfs_inode **new, const char *name, mode_t mode)
int hsi_nfs3_mknod (struct hsfs_inode *parent, struct hsfs_inode **new, const char *name, mode_t mode, dev_t rdev)
int hsi_nfs3_link (struct hsfs_inode *inode, struct hsfs_inode *newparent, struct hsfs_inode **new, const char *name)
int hsi_nfs3_lookup (struct hsfs_inode *parent, struct hsfs_inode **new, const char *name)
struct hsfs_inode * hsi_nfs3_alloc_node (struct hsfs_super *sb, nfs_fh3 *fh, uint64_t ino, fattr3 *attr)
struct hsfs_inode * hsi_nfs3_ifind (struct hsfs_super *sb, nfs_fh3 *fh, fattr3 *attr)
int hsi_nfs3_getattr (struct hsfs_inode *inode)
int hsi_nfs3_fattr2stat (struct fattr3 *attr, struct stat *st)
int hsi_nfs3_stat2sattr (struct stat *st, int to_set, struct hsfs_sattr *attr)
int hsi_nfs3_setattr (struct hsfs_inode *inode, struct hsfs_sattr *attr)
int hsi_nfs3_statfs (struct hsfs_inode *inode)
int hsi_super2statvfs (struct hsfs_super *sp, struct statvfs *stbuf)
int hsi_nfs3_readdir (struct hsfs_inode *parent, struct hsfs_readdir_ctx *hrc, size_t maxcount)
int hsi_nfs3_fsinfo (struct hsfs_inode *inode)
int hsi_nfs3_pathconf (struct hsfs_inode *inode)
int hsi_nfs3_clnt_call (struct hsfs_super *sb, CLIENT *clnt, unsigned long procnum, xdrproc_t inproc, char *in, xdrproc_t outproc, char *out)
int hsi_nfs3_getxattr (struct hsfs_inode *inode, u_int mask, struct posix_acl **pbuf, int type)
int hsi_nfs3_setxattr (struct hsfs_inode *inode, const char *value, int type, size_t size)
Function Documentation
int hsi_nfs3_mkdir (struct hsfs_inode * parent, struct hsfs_inode ** new, const char * name, mode_t mode)
Make a directory.
Parameters
parent[in] the information of the source parent directory
new[out] the information of the target directory
name[in] directory name
mode[in] the mode of the target directory
Returns
error number
Definition at line 16 of file hsi_nfs3_mkdir.c.
References mkdir3args::attributes, hsfs_super::clntp, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG_IN, DEBUG_OUT, diropargs3::dir, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_ifind(), hsi_nfs3_stat_to_errno(), hsfs_inode::ino, sattr3::mode, diropargs3::name, NFSPROC3_MKDIR, hsfs_inode::sb, set_uint32::set, set_uint32::set_uint32_u, set_uint32::val, mkdir3args::where, xdr_diropres3(), and xdr_mkdir3args().
Referenced by hsx_fuse_mkdir().
int hsi_nfs3_rmdir (struct hsfs_inode * parent, const char * name)
Remove a directory.
Parameters
parent[in] the information of the source parent directory
name[in] directory name
Returns
error number
Definition at line 16 of file hsi_nfs3_rmdir.c.
References hsfs_super::clntp, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG_IN, DEBUG_OUT, diropargs3::dir, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), hsfs_inode::ino, diropargs3::name, NFSPROC3_RMDIR, hsfs_inode::sb, xdr_diropargs3(), and xdr_wccstat3().
Referenced by hsx_fuse_rmdir().
int hsi_nfs3_unlink (struct hsfs_inode * parent, const char * name)
Remove a file.
Parameters
parent[in] the information of the parent directory
name[in] to remove
Returns
error number
Definition at line 92 of file hsi_nfs3_unlink.c.
References hsfs_inode::attr, hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, diropargs3::dir, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), hsfs_inode::ino, diropargs3::name, NFS3_OK, NFSPROC3_REMOVE, hsfs_inode::sb, xdr_diropargs3(), and xdr_wccstat3().
Referenced by hsx_fuse_unlink().
int hsi_nfs3_rename (struct hsfs_inode * parent, const char * name, struct hsfs_inode * newparent, const char * newname)
Rename a file.
Parameters
parent[in] the information of the source parent directory
name[in] source name
newparent[in] the information of the target parent directory
newname[in] target name
Returns
error number
Definition at line 31 of file hsi_nfs3_rename.c.
References hsfs_inode::attr, hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, diropargs3::dir, ERR, hsfs_inode::fh, rename3args::from, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), diropargs3::name, NFS3_OK, NFSPROC3_RENAME, hsfs_inode::sb, rename3args::to, xdr_rename3args(), and xdr_rename3res().
Referenced by hsx_fuse_rename().
int hsi_nfs3_stat_to_errno (int stat)
Change nfs3 status number to system error number.
Parameters
stat[in] nfs3 status number
Returns
error number
Definition at line 74 of file hsi_nfs3_unlink.c.
References nfs_err.
Referenced by hsi_nfs3_access(), hsi_nfs3_create(), hsi_nfs3_fsinfo(), hsi_nfs3_getattr(), hsi_nfs3_getxattr(), hsi_nfs3_link(), hsi_nfs3_lookup(), hsi_nfs3_mkdir(), hsi_nfs3_mknod(), hsi_nfs3_pathconf(), hsi_nfs3_read(), hsi_nfs3_readdir(), hsi_nfs3_readlink(), hsi_nfs3_rename(), hsi_nfs3_rmdir(), hsi_nfs3_setattr(), hsi_nfs3_setxattr(), hsi_nfs3_statfs(), hsi_nfs3_symlink(), hsi_nfs3_unlink(), and hsi_nfs3_write().
int hsi_rpc_stat_to_errno (CLIENT * clntp)
Change rpc status number to system error number.
Parameters
clntp[in] rpc client handle
Returns
error number
Definition at line 84 of file hsi_nfs3_unlink.c.
Referenced by hsi_nfs3_clnt_call().
int hsi_nfs3_readlink (struct hsfs_inode * inode, char ** link)
Read the contents of the symbolic link.
Parameters
inode[in] the struct hsfs_inode of the symbolic link
link[out] the contents of the symbolic link
Returns
error number
Definition at line 85 of file hsi_nfs3_readlink.c.
References hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), NFS3_OK, NFSPROC3_READLINK, hsfs_inode::sb, xdr_nfs_fh3(), and xdr_readlink3res().
Referenced by hsx_fuse_readlink().
int hsi_nfs3_symlink (struct hsfs_inode * parent, struct hsfs_inode ** new, const char * link, const char * name)
Create a symbolic link.
Parameters
parent[in] the struct hsfs_inode of the parent
new[out] the struct hsfs_inode of the new
link[in] the contents of the new symbolic link
name[in] the name of the new symbolic link
Returns
error number
Definition at line 86 of file hsi_nfs3_symlink.c.
References hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, diropargs3::dir, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_ifind(), hsi_nfs3_stat_to_errno(), diropargs3::name, NFS3_OK, NFSPROC3_SYMLINK, hsfs_inode::sb, symlink3args::symlink, symlinkdata3::symlink_data, symlink3args::where, xdr_diropres3(), and xdr_symlink3args().
Referenced by hsx_fuse_symlink().
int hsi_nfs3_read (struct hsfs_rw_info * rw)
Read file.
Parameters
rw[in,out] the content of the read operation
Returns
error number
Definition at line 7 of file hsi_nfs3_read.c.
References hsfs_inode::attr, post_op_attr::attributes, hsfs_super::clntp, read3args::count, read3resok::count, nfs_fh3::data, hsfs_rw_info::data, read3resok::data, nfs_fh3::data_len, hsfs_rw_info::data_len, read3resok::data_len, nfs_fh3::data_val, hsfs_rw_info::data_val, read3resok::data_val, DEBUG, DEBUG_IN, DEBUG_OUT, hsfs_rw_info::eof, read3resok::eof, ERR, hsfs_inode::fh, read3args::file, read3resok::file_attributes, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), hsfs_rw_info::inode, NFSPROC3_READ, read3args::offset, post_op_attr::post_op_attr_u, post_op_attr::present, read3res::read3res_u, read3res::resfail, read3res::resok, hsfs_rw_info::ret_count, hsfs_rw_info::rw_off, hsfs_rw_info::rw_size, hsfs_inode::sb, read3res::status, xdr_read3args(), and xdr_read3res().
Referenced by hsx_fuse_read().
int hsi_nfs3_write (struct hsfs_rw_info * rw)
Write file.
Parameters
rw[in,out] the content of the write operation
Returns
error number
Definition at line 7 of file hsi_nfs3_write.c.
References wcc_data::after, hsfs_inode::attr, post_op_attr::attributes, hsfs_super::clntp, write3args::count, write3resok::count, nfs_fh3::data, hsfs_rw_info::data, write3args::data, nfs_fh3::data_len, hsfs_rw_info::data_len, write3args::data_len, nfs_fh3::data_val, hsfs_rw_info::data_val, write3args::data_val, DEBUG, DEBUG_IN, DEBUG_OUT, ERR, hsfs_inode::fh, write3args::file, write3resok::file_wcc, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), hsfs_rw_info::inode, NFSPROC3_WRITE, write3args::offset, post_op_attr::post_op_attr_u, post_op_attr::present, write3res::resfail, write3res::resok, hsfs_rw_info::ret_count, hsfs_rw_info::rw_off, hsfs_rw_info::rw_size, hsfs_inode::sb, hsfs_rw_info::stable, write3args::stable, write3res::status, write3res::write3res_u, xdr_write3args(), and xdr_write3res().
Referenced by hsx_fuse_write().
int hsi_nfs3_access (struct hsfs_inode * inode, int mask)
Request permission to an operation.
Parameters
inode[in] the information of the inode requested
mask[in] the permission requested
Returns
error number
Definition at line 20 of file hsi_nfs3_access.c.
References access3args::access, hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, hsfs_inode::fh, FULL_ACCESS, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), NFSPROC3_ACCESS, access3args::object, hsfs_inode::sb, access3res::status, xdr_access3args(), and xdr_access3res().
Referenced by hsx_fuse_access().
int hsi_nfs3_create (struct hsfs_inode * parent, struct hsfs_inode ** new, const char * name, mode_t mode)
Create a regular file.
Parameters
parent[in] the information of the parent directory
new[out] the information of the file created
name[in] the name of the file you want to create
mode[in] the access mode of the file
Returns
error number
Definition at line 18 of file hsi_nfs3_create.c.
References sattr3::atime, hsfs_inode::attr, hsfs_super::clntp, createhow3::createhow3_u, DEBUG_IN, DEBUG_OUT, diropargs3::dir, EXCLUSIVE, hsfs_inode::fh, FULL_MODE, fattr3::gid, sattr3::gid, create3args::how, hsi_nfs3_clnt_call(), hsi_nfs3_ifind(), hsi_nfs3_setattr(), hsi_nfs3_stat_to_errno(), hsfs_inode::ino, hsfs_sattr::mode, sattr3::mode, createhow3::mode, sattr3::mtime, diropargs3::name, NFS3_CREATEVERFSIZE, NFS3_OK, NFSPROC3_CREATE, createhow3::obj_attributes, S_SETMODE, hsfs_inode::sb, set_uint32::set, set_uint64::set, set_time::set, SET_TO_SERVER_TIME, set_uint32::set_uint32_u, sattr3::size, diropres3::status, fattr3::uid, sattr3::uid, set_uint32::val, createhow3::verf, WARNING, create3args::where, xdr_create3args(), and xdr_diropres3().
Referenced by hsx_fuse_create().
int hsi_nfs3_mknod (struct hsfs_inode * parent, struct hsfs_inode ** new, const char * name, mode_t mode, dev_t rdev)
Create a special file.
Parameters
parent[in] the inode of the parent directory
new[out] the inode of the created file
name[in] the name to create
mode[in] file type and access mode of the file
rdev[in] device number of the file: only used for CHR and BLK
Returns
error number
Definition at line 135 of file hsi_nfs3_mknod.c.
References wcc_data::after, hsfs_inode::attr, hsfs_super::clntp, nfs_fh3::data, DEBUG_IN, DEBUG_OUT, devicedata3::dev_attributes, mknoddata3::device, diropargs3::dir, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_ifind(), hsi_nfs3_stat_to_errno(), hsfs_inode::ino, specdata3::major, specdata3::minor, mknoddata3::mknoddata3_u, sattr3::mode, diropargs3::name, NF3BLK, NF3CHR, NF3FIFO, NF3SOCK, NFSPROC3_MKNOD, hsfs_inode::nlookup, diropres3ok::obj_attributes, mknoddata3::pipe_attributes, post_op_attr::post_op_attr_u, diropres3::resfail, diropres3::resok, hsfs_inode::sb, set_uint32::set, devicedata3::spec, mknoddata3::type, set_uint32::val, mknod3args::what, mknod3args::where, xdr_diropres3(), and xdr_mknod3args().
Referenced by hsx_fuse_mknod().
int hsi_nfs3_link (struct hsfs_inode * inode, struct hsfs_inode * newparent, struct hsfs_inode ** new, const char * name)
Create a hard link to a file.
Parameters
inode[in] the inode of the file
newparent[in] the inode of the new parent
new[out] the inode of the linked file
name[in] the name to of the link to create
Returns
error number
Definition at line 105 of file hsi_nfs3_link.c.
References hsfs_inode::attr, hsfs_super::clntp, nfs_fh3::data, DEBUG_IN, DEBUG_OUT, diropargs3::dir, ERR, hsfs_inode::fh, link3args::file, hsi_nfs3_clnt_call(), hsi_nfs3_ifind(), hsi_nfs3_stat_to_errno(), hsfs_inode::ino, link3args::link, diropargs3::name, NFSPROC3_LINK, hsfs_inode::nlookup, hsfs_inode::sb, xdr_link3args(), and xdr_link3res().
Referenced by hsx_fuse_link().
int hsi_nfs3_lookup (struct hsfs_inode * parent, struct hsfs_inode ** new, const char * name)
Look up a directory entry by name.
Parameters
parent[in] The information of the parent node
new[out] Point to the node information obtained by name
name[in] The name to look up
Returns
error number
Definition at line 13 of file hsi_nfs3_lookup.c.
References hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, diropargs3::dir, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_ifind(), hsi_nfs3_stat_to_errno(), diropargs3::name, NFS3_OK, NFSPROC3_LOOKUP, hsfs_inode::sb, xdr_diropargs3(), and xdr_lookup3res().
Referenced by hsx_fuse_lookup().
struct hsfs_inode* hsi_nfs3_alloc_node (struct hsfs_super * sb, nfs_fh3 * fh, uint64_t ino, fattr3 * attr) read
Allocate memory for a node.
Parameters
sb[in] the information of the superblock
fh[in] a pointer to the filehandle of node
ino[in] the inode number
attr[in] a pointer to the attributes of node
Returns
a pointer to the object if successfull,else NULL
Definition at line 51 of file hsfs_fuse_table.c.
References hsfs_inode::attr, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, hsfs_inode::fh, hsfs_inode::generation, hsfs_inode::ino, hsfs_inode::nlookup, and hsfs_inode::sb.
Referenced by hsi_nfs3_ifind().
struct hsfs_inode* hsi_nfs3_ifind (struct hsfs_super * sb, nfs_fh3 * fh, fattr3 * attr) read
Look up a node from hash table.
Parameters
sb[in] The information of the superblock
fh[in] Filehandle of the parent directory
attr[in] Node attributes
Returns
a pointer to the node information
Definition at line 135 of file hsfs_fuse_table.c.
References hsfs_inode::attr, DEBUG, fattr3::fileid, hsi_nfs3_alloc_node(), hsx_fuse_iadd(), hsx_fuse_iget(), hsfs_inode::ino, and hsfs_inode::nlookup.
Referenced by hsi_nfs3_create(), hsi_nfs3_link(), hsi_nfs3_lookup(), hsi_nfs3_mkdir(), hsi_nfs3_mknod(), and hsi_nfs3_symlink().
int hsi_nfs3_getattr (struct hsfs_inode * inode)
Get file attributes.
Parameters
inode[in,out] the info of file containing the attributes as return
Returns
error number
Definition at line 3 of file hsi_nfs3_getattr.c.
References fattr3::atime, hsfs_inode::attr, hsfs_super::clntp, fattr3::ctime, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG_IN, DEBUG_OUT, ERR, hsfs_inode::fh, fattr3::fileid, fattr3::fsid, fattr3::gid, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), specdata3::major, specdata3::minor, fattr3::mode, fattr3::mtime, NFS3_OK, NFSPROC3_GETATTR, fattr3::nlink, nfstime3::nseconds, fattr3::rdev, hsfs_inode::sb, nfstime3::seconds, fattr3::size, fattr3::type, fattr3::uid, fattr3::used, xdr_getattr3res(), and xdr_nfs_fh3().
Referenced by hsx_fuse_getattr().
int hsi_nfs3_fattr2stat (struct fattr3 * attr, struct stat * st)
Convert struct fattr3 to struct stat.
Parameters
attr[in] the attributes
st[out] the result of the convertion
Returns
error number
Definition at line 4 of file hsi_nfs3_fattr2stat.c.
References fattr3::atime, fattr3::ctime, DEBUG_IN, DEBUG_OUT, fattr3::fileid, fattr3::gid, specdata3::major, specdata3::minor, fattr3::mode, fattr3::mtime, NF3BLK, NF3CHR, NF3DIR, NF3FIFO, NF3LNK, NF3REG, NF3SOCK, fattr3::nlink, nfstime3::nseconds, fattr3::rdev, nfstime3::seconds, fattr3::size, fattr3::type, fattr3::uid, and fattr3::used.
Referenced by hsi_nfs3_readdir(), hsx_fuse_fill_reply(), hsx_fuse_getattr(), and hsx_fuse_setattr().
int hsi_nfs3_stat2sattr (struct stat * st, int to_set, struct hsfs_sattr * attr)
Convert struct stat to struct hsfs_sattr.
Parameters
st[in] the struct stat of file attributes
to_set[in] bit mask of attributes which should be set
attr[out] the result of the convertion
Returns
error number
Definition at line 4 of file hsi_nfs3_stat2sattr.c.
References hsfs_sattr::atime, DEBUG_IN, DEBUG_OUT, ERR, hsfs_sattr::gid, hsfs_sattr::mode, hsfs_sattr::mtime, hsfs_sattr::size, hsfs_sattr::uid, and hsfs_sattr::valid.
Referenced by hsx_fuse_setattr().
int hsi_nfs3_setattr (struct hsfs_inode * inode, struct hsfs_sattr * attr)
Set file attributes.
Parameters
inode[in,out] the info of file containing the attributes as return
attr[in] the attributes
Returns
error number
Definition at line 4 of file hsi_nfs3_setattr.c.
References fattr3::atime, hsfs_sattr::atime, sattr3::atime, hsfs_inode::attr, sattrguard3::check, hsfs_super::clntp, fattr3::ctime, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG_IN, DEBUG_OUT, DONT_CHANGE, ERR, hsfs_inode::fh, fattr3::fileid, fattr3::fsid, fattr3::gid, hsfs_sattr::gid, sattr3::gid, setattr3args::guard, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), specdata3::major, specdata3::minor, fattr3::mode, hsfs_sattr::mode, sattr3::mode, fattr3::mtime, hsfs_sattr::mtime, sattr3::mtime, setattr3args::new_attributes, NFS3_OK, NFSPROC3_SETATTR, fattr3::nlink, nfstime3::nseconds, setattr3args::object, fattr3::rdev, S_ISSETATIME, S_ISSETATIMENOW, S_ISSETGID, S_ISSETMODE, S_ISSETMTIME, S_ISSETMTIMENOW, S_ISSETSIZE, S_ISSETUID, hsfs_inode::sb, nfstime3::seconds, set_uint32::set, set_uint64::set, set_time::set, set_time::set_time_u, SET_TO_CLIENT_TIME, SET_TO_SERVER_TIME, set_uint32::set_uint32_u, set_uint64::set_uint64_u, fattr3::size, hsfs_sattr::size, sattr3::size, set_time::time, fattr3::type, fattr3::uid, hsfs_sattr::uid, sattr3::uid, fattr3::used, set_uint32::val, set_uint64::val, hsfs_sattr::valid, xdr_setattr3args(), and xdr_wccstat3().
Referenced by hsi_nfs3_create(), and hsx_fuse_setattr().
int hsi_nfs3_statfs (struct hsfs_inode * inode)
Get Dynamic file system information.
Parameters
inode[in,out] the information of inode
Returns
error number
Definition at line 3 of file hsi_nfs3_statfs.c.
References hsfs_super::abytes, fsstat3resok::abytes, hsfs_super::afiles, fsstat3resok::afiles, hsfs_super::clntp, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG_IN, DEBUG_OUT, ERR, hsfs_super::fbytes, fsstat3resok::fbytes, hsfs_super::ffiles, fsstat3resok::ffiles, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), NFS3_OK, NFSPROC3_FSSTAT, hsfs_inode::sb, hsfs_super::tbytes, fsstat3resok::tbytes, hsfs_super::tfiles, fsstat3resok::tfiles, xdr_fsstat3res(), and xdr_nfs_fh3().
Referenced by hsx_fuse_statfs().
int hsi_super2statvfs (struct hsfs_super * sp, struct statvfs * stbuf)
Change some fileds of hsfs_super to statvfs.
Parameters
sp[in] the information of hsfs_super
stbuf[out] the information of the file system
Returns
error number
Definition at line 36 of file hsx_fuse_statfs.c.
References hsfs_super::abytes, hsfs_super::afiles, hsfs_super::bsize, hsfs_super::bsize_bits, ERR, hsfs_super::fbytes, hsfs_super::ffiles, hsfs_super::flags, hsfs_super::namlen, hsfs_super::tbytes, and hsfs_super::tfiles.
Referenced by hsx_fuse_statfs().
int hsi_nfs3_readdir (struct hsfs_inode * parent, struct hsfs_readdir_ctx * hrc, size_t maxcount)
Read dir.
Parameters
parent[in] get the file handle
hrc[in,out] the content of the fuse_add_direntry and fi->fh
maxcount[out] the maximum size of the server return in bytes
Returns
error number
Definition at line 11 of file hsi_nfs3_readdir.c.
References hsfs_super::clntp, readdirplus3args::cookie, entryplus3::cookie, hsfs_readdir_ctx::cookieverf, readdirplus3args::cookieverf, readdirplus3resok::cookieverf, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG_IN, DEBUG_OUT, readdirplus3args::dir, readdirplus3resok::dir_attributes, readdirplus3args::dircount, dirlistplus3::entries, dirlistplus3::eof, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_fattr2stat(), hsi_nfs3_stat_to_errno(), readdirplus3args::maxcount, hsfs_readdir_ctx::name, entryplus3::name, entryplus3::name_attributes, hsfs_readdir_ctx::next, entryplus3::nextentry, NFS3_COOKIEVERFSIZE, NFS3_OK, NFSPROC3_READDIRPLUS, hsfs_readdir_ctx::off, post_op_attr::present, readdirplus3res::readdirplus3res_u, readdirplus3resok::reply, readdirplus3res::resok, hsfs_inode::sb, readdirplus3res::status, hsfs_readdir_ctx::stbuf, xdr_readdirplus3args(), and xdr_readdirplus3res().
Referenced by hsx_fuse_readdir().
int hsi_nfs3_fsinfo (struct hsfs_inode * inode)
Get static file system information of NFS
Parameters
inode[in] hsfs inode of root directory
Returns
errno number as Linux system
Definition at line 46 of file hsi_nfs3_fsinfo.c.
References hsfs_inode::attr, post_op_attr::attributes, hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, ERR, hsfs_inode::fh, fsinfo3res::fsinfo3res_u, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), hsfs_inode::ino, NFSPROC3_FSINFO, fsinfo3resok::obj_attributes, post_op_attr::post_op_attr_u, post_op_attr::present, fsinfo3res::resok, hsfs_super::root, hsfs_inode::sb, fsinfo3res::status, xdr_fsinfo3res(), and xdr_nfs_fh3().
int hsi_nfs3_pathconf (struct hsfs_inode * inode)
Retrieve POSIX information of NFS.
Parameters
inode[in] hsfs inode of root directory
Returns
errno number as Linux system
Definition at line 5 of file hsi_nfs3_pathconf.c.
References hsfs_inode::attr, post_op_attr::attributes, hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), hsfs_inode::ino, pathconf3resok::name_max, hsfs_super::namlen, NFSPROC3_PATHCONF, pathconf3resok::obj_attributes, pathconf3res::pathconf3res_u, post_op_attr::post_op_attr_u, post_op_attr::present, pathconf3res::resok, hsfs_super::root, hsfs_inode::sb, pathconf3res::status, xdr_nfs_fh3(), and xdr_pathconf3res().
int hsi_nfs3_clnt_call (struct hsfs_super * sb, CLIENT * clnt, unsigned long procnum, xdrproc_t inproc, char * in, xdrproc_t outproc, char * out)
Potting clnt_call.
Parameters
sb[in] super block of hsfs
clnt[in] CLIENT info
procnum[in] NFS procedure number(macro defined in nfs3.h)
inproc[in] function which is used to encode the procedure's parameters
in[in] the address of the procedure's argument(s)
outproc[in] function which is used to decode the procedure's results
out[out] the address of where to place the result(s)
Returns
errno number as Linux system
Definition at line 824 of file hsi_nfs3_mount.c.
References ERR, hsi_rpc_stat_to_errno(), and hsfs_super::timeo.
Referenced by hsi_nfs3_access(), hsi_nfs3_create(), hsi_nfs3_fsinfo(), hsi_nfs3_getattr(), hsi_nfs3_getxattr(), hsi_nfs3_link(), hsi_nfs3_lookup(), hsi_nfs3_mkdir(), hsi_nfs3_mknod(), hsi_nfs3_pathconf(), hsi_nfs3_read(), hsi_nfs3_readdir(), hsi_nfs3_readlink(), hsi_nfs3_rename(), hsi_nfs3_rmdir(), hsi_nfs3_setattr(), hsi_nfs3_setxattr(), hsi_nfs3_statfs(), hsi_nfs3_symlink(), hsi_nfs3_unlink(), and hsi_nfs3_write().
int hsi_nfs3_getxattr (struct hsfs_inode * inode, u_int mask, struct posix_acl ** pbuf, int type)
Get extended attribute.
Parameters
inode[in] the information of the node
mask[in] attribute mask
pbuf[out] point nodes acl information
type[in] acl type
Returns
error number as Linux system
Definition at line 10 of file hsi_nfs3_getxattr.c.
References hsfs_super::acl_clntp, ACL_TYPE_ACCESS, ACL_TYPE_DEFAULT, secattr::aclent, secattr::aclent_len, secattr::aclent_val, ACLPROC3_GETACL, hsfs_super::clntp, DEBUG, DEBUG_IN, DEBUG_OUT, secattr::dfaclent, secattr::dfaclent_len, secattr::dfaclent_val, ERR, GETACL3args::fh, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), aclent::id, secattr::mask, GETACL3args::mask, NFS3_OK, aclent::perm, posix_acl_alloc(), hsfs_inode::sb, aclent::type, xdr_GETACL3args(), and xdr_GETACL3res().
Referenced by hsi_nfs3_setxattr(), and hsx_fuse_getxattr().
int hsi_nfs3_setxattr (struct hsfs_inode * inode, const char * value, int type, size_t size)
Set extended attribute.
Parameters
inode[in] the hsfs_inode struct
value[in] data of attributes
type[in] the mode of extended attributes
size[in] the value size
Returns
errno number as Linux system
Definition at line 7 of file hsi_nfs3_setxattr.c.
References posix_acl::a_count, posix_acl::a_entries, SETACL3args::acl, hsfs_super::acl_clntp, ACL_TYPE_ACCESS, ACL_TYPE_DEFAULT, secattr::aclcnt, secattr::aclent, secattr::aclent_len, secattr::aclent_val, ACLPROC3_SETACL, hsfs_inode::attr, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG, DEBUG_IN, secattr::dfaclcnt, secattr::dfaclent, secattr::dfaclent_len, secattr::dfaclent_val, posix_acl_entry::e_id, posix_acl_entry::e_perm, posix_acl_entry::e_tag, hsfs_inode::fh, SETACL3args::fh, hsi_nfs3_clnt_call(), hsi_nfs3_getxattr(), hsi_nfs3_stat_to_errno(), aclent::id, hsfs_inode::ino, secattr::mask, fattr3::mode, NA_ACL, NA_ACLCNT, NA_DFACL, NA_DFACLCNT, NFS3_DIR, NFS_ACL, NFS_DFACL, aclent::perm, posix_acl_from_mode(), posix_acl_from_xattr(), hsfs_inode::sb, aclent::type, fattr3::type, xdr_SETACL3args(), and xdr_SETACL3res().
Referenced by hsx_fuse_setxattr().