hsfs: /hsfs/nfs3/hsi_nfs3_access.c File Reference
hsi_nfs3_access.c File Reference
#include "hsi_nfs3.h"
#include "log.h"
#include "nfs3.h"
Macros
#define FULL_ACCESS
Functions
int hsi_nfs3_access (struct hsfs_inode *hi, int mask)
Macro Definition Documentation
#define FULL_ACCESS
Value:
(ACCESS3_READ | ACCESS3_LOOKUP | ACCESS3_MODIFY \
                | ACCESS3_EXTEND | ACCESS3_DELETE |ACCESS3_EXECUTE )
Definition at line 17 of file hsi_nfs3_access.c.
Referenced by hsi_nfs3_access().
Function Documentation
int hsi_nfs3_access (struct hsfs_inode * inode, int mask)
Request permission to an operation.
Parameters
inode[in] the information of the inode requested
mask[in] the permission requested
Returns
error number
Definition at line 20 of file hsi_nfs3_access.c.
References access3args::access, hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, hsfs_inode::fh, FULL_ACCESS, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), NFSPROC3_ACCESS, access3args::object, hsfs_inode::sb, access3res::status, xdr_access3args(), and xdr_access3res().
Referenced by hsx_fuse_access().