hsfs: /hsfs/nfs3/hsi_nfs3_statfs.c File Reference
hsi_nfs3_statfs.c File Reference
#include "hsi_nfs3.h"
Functions
int hsi_nfs3_statfs (struct hsfs_inode *inode)
Function Documentation
int hsi_nfs3_statfs (struct hsfs_inode * inode)
Get Dynamic file system information.
Parameters
inode[in,out] the information of inode
Returns
error number
Definition at line 3 of file hsi_nfs3_statfs.c.
References hsfs_super::abytes, fsstat3resok::abytes, hsfs_super::afiles, fsstat3resok::afiles, hsfs_super::clntp, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG_IN, DEBUG_OUT, ERR, hsfs_super::fbytes, fsstat3resok::fbytes, hsfs_super::ffiles, fsstat3resok::ffiles, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), NFS3_OK, NFSPROC3_FSSTAT, hsfs_inode::sb, hsfs_super::tbytes, fsstat3resok::tbytes, hsfs_super::tfiles, fsstat3resok::tfiles, xdr_fsstat3res(), and xdr_nfs_fh3().
Referenced by hsx_fuse_statfs().