hsfs: /hsfs/nfs3/hsi_nfs3_rename.c File Reference
hsi_nfs3_rename.c File Reference
#include "hsi_nfs3.h"
Functions
int hsi_nfs3_rename (struct hsfs_inode *parent, const char *name, struct hsfs_inode *newparent, const char *newname)
Function Documentation
int hsi_nfs3_rename (struct hsfs_inode * parent, const char * name, struct hsfs_inode * newparent, const char * newname)
Rename a file.
Parameters
parent[in] the information of the source parent directory
name[in] source name
newparent[in] the information of the target parent directory
newname[in] target name
Returns
error number
Definition at line 31 of file hsi_nfs3_rename.c.
References hsfs_inode::attr, hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, diropargs3::dir, ERR, hsfs_inode::fh, rename3args::from, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), diropargs3::name, NFS3_OK, NFSPROC3_RENAME, hsfs_inode::sb, rename3args::to, xdr_rename3args(), and xdr_rename3res().
Referenced by hsx_fuse_rename().