hsfs: /hsfs/nfs3/hsi_nfs3_setattr.c File Reference
hsi_nfs3_setattr.c File Reference
#include <errno.h>
#include "hsi_nfs3.h"
Functions
int hsi_nfs3_setattr (struct hsfs_inode *inode, struct hsfs_sattr *attr)
Function Documentation
int hsi_nfs3_setattr (struct hsfs_inode * inode, struct hsfs_sattr * attr)
Set file attributes.
Parameters
inode[in,out] the info of file containing the attributes as return
attr[in] the attributes
Returns
error number
Definition at line 4 of file hsi_nfs3_setattr.c.
References fattr3::atime, hsfs_sattr::atime, sattr3::atime, hsfs_inode::attr, sattrguard3::check, hsfs_super::clntp, fattr3::ctime, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG_IN, DEBUG_OUT, DONT_CHANGE, ERR, hsfs_inode::fh, fattr3::fileid, fattr3::fsid, fattr3::gid, hsfs_sattr::gid, sattr3::gid, setattr3args::guard, hsi_nfs3_clnt_call(), hsi_nfs3_stat_to_errno(), specdata3::major, specdata3::minor, fattr3::mode, hsfs_sattr::mode, sattr3::mode, fattr3::mtime, hsfs_sattr::mtime, sattr3::mtime, setattr3args::new_attributes, NFS3_OK, NFSPROC3_SETATTR, fattr3::nlink, nfstime3::nseconds, setattr3args::object, fattr3::rdev, S_ISSETATIME, S_ISSETATIMENOW, S_ISSETGID, S_ISSETMODE, S_ISSETMTIME, S_ISSETMTIMENOW, S_ISSETSIZE, S_ISSETUID, hsfs_inode::sb, nfstime3::seconds, set_uint32::set, set_uint64::set, set_time::set, set_time::set_time_u, SET_TO_CLIENT_TIME, SET_TO_SERVER_TIME, set_uint32::set_uint32_u, set_uint64::set_uint64_u, fattr3::size, hsfs_sattr::size, sattr3::size, set_time::time, fattr3::type, fattr3::uid, hsfs_sattr::uid, sattr3::uid, fattr3::used, set_uint32::val, set_uint64::val, hsfs_sattr::valid, xdr_setattr3args(), and xdr_wccstat3().
Referenced by hsi_nfs3_create(), and hsx_fuse_setattr().