hsfs: /hsfs/nfs3/hsi_nfs3_lookup.c File Reference
hsi_nfs3_lookup.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include "hsi_nfs3.h"
Functions
int hsi_nfs3_lookup (struct hsfs_inode *parent, struct hsfs_inode **new, const char *name)
Function Documentation
int hsi_nfs3_lookup (struct hsfs_inode * parent, struct hsfs_inode ** new, const char * name)
Look up a directory entry by name.
Parameters
parent[in] The information of the parent node
new[out] Point to the node information obtained by name
name[in] The name to look up
Returns
error number
Definition at line 13 of file hsi_nfs3_lookup.c.
References hsfs_super::clntp, DEBUG_IN, DEBUG_OUT, diropargs3::dir, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_ifind(), hsi_nfs3_stat_to_errno(), diropargs3::name, NFS3_OK, NFSPROC3_LOOKUP, hsfs_inode::sb, xdr_diropargs3(), and xdr_lookup3res().
Referenced by hsx_fuse_lookup().