hsfs: /hsfs/nfs3/hsi_acl3.c File Reference
hsi_acl3.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include "hsfs.h"
#include "acl.h"
Macros
#define atomic_set(v, i) ((v)->counter = (i))
Functions
struct posix_acl * posix_acl_alloc (int count)
int posix_acl_to_xattr (const struct posix_acl *acl, void *buffer, size_t size)
struct posix_acl * posix_acl_from_xattr (const void *value, size_t size)
struct posix_acl * posix_acl_from_mode (mode_t mode)
Macro Definition Documentation
#define atomic_set (v, i) ((v)->counter = (i))
Definition at line 8 of file hsi_acl3.c.
Referenced by posix_acl_alloc().
Function Documentation
struct posix_acl* posix_acl_alloc (int count) read
Definition at line 12 of file hsi_acl3.c.
References posix_acl::a_count, posix_acl::a_refcount, and atomic_set.
Referenced by hsi_nfs3_getxattr(), posix_acl_from_mode(), and posix_acl_from_xattr().
int posix_acl_to_xattr (const struct posix_acl * acl, void * buffer, size_t size)
Definition at line 27 of file hsi_acl3.c.
References posix_acl::a_count, posix_acl::a_entries, posix_acl_xattr_header::a_entries, posix_acl_xattr_header::a_version, posix_acl_entry::e_id, posix_acl_xattr_entry::e_id, posix_acl_entry::e_perm, posix_acl_xattr_entry::e_perm, posix_acl_entry::e_tag, posix_acl_xattr_entry::e_tag, and POSIX_ACL_XATTR_VERSION.
Referenced by hsx_fuse_getxattr().
struct posix_acl* posix_acl_from_xattr (const void * value, size_t size) read
Definition at line 57 of file hsi_acl3.c.
References posix_acl::a_entries, posix_acl_xattr_header::a_version, ACL_GROUP, ACL_GROUP_OBJ, ACL_MASK, ACL_OTHER, ACL_UNDEFINED_ID, ACL_USER, ACL_USER_OBJ, posix_acl_entry::e_id, posix_acl_xattr_entry::e_id, posix_acl_entry::e_perm, posix_acl_xattr_entry::e_perm, posix_acl_entry::e_tag, posix_acl_xattr_entry::e_tag, posix_acl_alloc(), and POSIX_ACL_XATTR_VERSION.
Referenced by hsi_nfs3_setxattr().
struct posix_acl* posix_acl_from_mode (mode_t mode) read
Definition at line 119 of file hsi_acl3.c.
References posix_acl::a_entries, ACL_GROUP_OBJ, ACL_OTHER, ACL_UNDEFINED_ID, ACL_USER_OBJ, posix_acl_entry::e_id, posix_acl_entry::e_perm, posix_acl_entry::e_tag, and posix_acl_alloc().
Referenced by hsi_nfs3_setxattr().