hsfs: /hsfs/nfs3/hsi_nfs3_readdir.c File Reference
hsi_nfs3_readdir.c File Reference
#include <errno.h>
#include "hsfs.h"
#include "hsi_nfs3.h"
#include "log.h"
Functions
int hsi_nfs3_readdir (struct hsfs_inode *parent, struct hsfs_readdir_ctx *hrc, size_t maxcount)
Function Documentation
int hsi_nfs3_readdir (struct hsfs_inode * parent, struct hsfs_readdir_ctx * hrc, size_t maxcount)
Read dir.
Parameters
parent[in] get the file handle
hrc[in,out] the content of the fuse_add_direntry and fi->fh
maxcount[out] the maximum size of the server return in bytes
Returns
error number
Definition at line 11 of file hsi_nfs3_readdir.c.
References hsfs_super::clntp, readdirplus3args::cookie, entryplus3::cookie, hsfs_readdir_ctx::cookieverf, readdirplus3args::cookieverf, readdirplus3resok::cookieverf, nfs_fh3::data, nfs_fh3::data_len, nfs_fh3::data_val, DEBUG_IN, DEBUG_OUT, readdirplus3args::dir, readdirplus3resok::dir_attributes, readdirplus3args::dircount, dirlistplus3::entries, dirlistplus3::eof, ERR, hsfs_inode::fh, hsi_nfs3_clnt_call(), hsi_nfs3_fattr2stat(), hsi_nfs3_stat_to_errno(), readdirplus3args::maxcount, hsfs_readdir_ctx::name, entryplus3::name, entryplus3::name_attributes, hsfs_readdir_ctx::next, entryplus3::nextentry, NFS3_COOKIEVERFSIZE, NFS3_OK, NFSPROC3_READDIRPLUS, hsfs_readdir_ctx::off, post_op_attr::present, readdirplus3res::readdirplus3res_u, readdirplus3resok::reply, readdirplus3res::resok, hsfs_inode::sb, readdirplus3res::status, hsfs_readdir_ctx::stbuf, xdr_readdirplus3args(), and xdr_readdirplus3res().
Referenced by hsx_fuse_readdir().