hsfs: /hsfs/include/hsx_fuse.h File Reference
hsx_fuse.h File Reference
#include <sys/stat.h>
Functions
void hsx_fuse_init (void *data, struct fuse_conn_info *conn)
void hsx_fuse_mkdir (fuse_req_t req, fuse_ino_t parent, const char *name, mode_t mode)
void hsx_fuse_rmdir (fuse_req_t req, fuse_ino_t parent, const char *name)
int hsx_fuse_fill_reply (struct hsfs_inode *inode, struct fuse_entry_param *e)
void hsx_fuse_read (fuse_req_t req, fuse_ino_t ino, size_t size, off_t off, struct fuse_file_info *fi)
void hsx_fuse_write (fuse_req_t req, fuse_ino_t ino, const char *buf, size_t size, off_t off, struct fuse_file_info *fi)
void hsx_fuse_unlink (fuse_req_t req, fuse_ino_t parent, const char *name)
void hsx_fuse_rename (fuse_req_t req, fuse_ino_t parent, const char *name, fuse_ino_t newparent, const char *newname)
void hsx_fuse_readlink (fuse_req_t req, fuse_ino_t ino)
void hsx_fuse_symlink (fuse_req_t req, const char *link, fuse_ino_t parent, const char *name)
void hsx_fuse_access (fuse_req_t req, fuse_ino_t ino, int mask)
void hsx_fuse_create (fuse_req_t req, fuse_ino_t parent, const char *name, mode_t mode, struct fuse_file_info *fi)
void hsx_fuse_mknod (fuse_req_t req, fuse_ino_t parent, const char *name, mode_t mode, dev_t rdev)
void hsx_fuse_link (fuse_req_t req, fuse_ino_t ino, fuse_ino_t newparent, const char *newname)
void hsx_fuse_lookup (fuse_req_t req, fuse_ino_t ino, const char *name)
void hsx_fuse_forget (fuse_req_t req, fuse_ino_t ino, unsigned long nlookup)
void hsx_fuse_open (fuse_req_t req, fuse_ino_t ino, struct fuse_file_info *fi)
void hsx_fuse_release (fuse_req_t req, fuse_ino_t ino, struct fuse_file_info *fi)
void hsx_fuse_getattr (fuse_req_t req, fuse_ino_t ino, struct fuse_file_info *fi)
void hsx_fuse_setattr (fuse_req_t req, fuse_ino_t ino, struct stat *attr, int to_set, struct fuse_file_info *fi)
void hsx_fuse_statfs (fuse_req_t req, fuse_ino_t ino)
void hsx_fuse_readdir (fuse_req_t req, fuse_ino_t ino, size_t size, off_t off, struct fuse_file_info *fi)
void hsx_fuse_opendir (fuse_req_t req, fuse_ino_t ino, struct fuse_file_info *fi)
struct fuse_chan * hsx_fuse_mount (const char *spec, const char *point, struct fuse_args *args, char *udata, struct hsfs_super *super)
int hsx_fuse_unmount (const char *spec, const char *point, struct fuse_chan *ch, struct hsfs_super *super)
void hsx_fuse_getxattr (fuse_req_t req, fuse_ino_t ino, const char *name, size_t size)
void hsx_fuse_setxattr (fuse_req_t req, fuse_ino_t ino, const char *name, const char *value, size_t size, int flags)
Function Documentation
void hsx_fuse_init (void * data, struct fuse_conn_info * conn)
void hsx_fuse_mkdir (fuse_req_t req, fuse_ino_t parent, const char * name, mode_t mode)
Make a directory.
Valid replies: fuse_reply_err fuse_reply_entry
Parameters
req[in] request handle
parent[in] inode number of the parent directory
name[in] to make
mode[in] the mode to make
Definition at line 6 of file hsx_fuse_mkdir.c.
References DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_mkdir(), hsx_fuse_fill_reply(), and hsx_fuse_iget().
void hsx_fuse_rmdir (fuse_req_t req, fuse_ino_t parent, const char * name)
Remove a directory.
Valid replies: fuse_reply_err
Parameters
req[in] request handle
parent[in] inode number of the parent directory
name[in] to remove
Definition at line 5 of file hsx_fuse_rmdir.c.
References DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_rmdir(), and hsx_fuse_iget().
int hsx_fuse_fill_reply (struct hsfs_inode * inode, struct fuse_entry_param * e)
Fill the param in the entry.
Parameters
inode[in] data of hsfs_inode
e[in] the param of the entry
Returns
the error number of the function
Definition at line 5 of file hsx_fuse_fill_reply.c.
References hsfs_super::acdirmax, hsfs_super::acdirmin, hsfs_super::acregmax, hsfs_super::acregmin, hsfs_inode::attr, DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_fattr2stat(), hsfs_inode::ino, NF3DIR, NF3REG, hsfs_inode::sb, and fattr3::type.
Referenced by hsx_fuse_create(), hsx_fuse_link(), hsx_fuse_lookup(), hsx_fuse_mkdir(), hsx_fuse_mknod(), and hsx_fuse_symlink().
void hsx_fuse_read (fuse_req_t req, fuse_ino_t ino, size_t size, off_t off, struct fuse_file_info * fi)
Read data.
Valid replies: fuse_reply_buf fuse_reply_err
Parameters
req[in] request handle
ino[in] the inode number
size[in] number of bytes to read
off[in] offset to read from
fi[in] file information
Definition at line 6 of file hsx_fuse_read.c.
References hsfs_rw_info::data, hsfs_rw_info::data_len, hsfs_rw_info::data_val, DEBUG, DEBUG_IN, DEBUG_OUT, hsfs_rw_info::eof, hsi_nfs3_read(), hsx_fuse_iget(), hsfs_inode::ino, hsfs_rw_info::inode, min, hsfs_rw_info::ret_count, hsfs_super::rsize, hsfs_rw_info::rw_off, and hsfs_rw_info::rw_size.
void hsx_fuse_write (fuse_req_t req, fuse_ino_t ino, const char * buf, size_t size, off_t off, struct fuse_file_info * fi)
Write data.
Valid replies: fuse_reply_write fuse_reply_err
Parameters
req[in] request handle
ino[in] the inode number
buf[in] data to write
size[in] number of bytes to write
off[in] offset to read from
fi[in] file information
Definition at line 6 of file hsx_fuse_write.c.
References hsfs_rw_info::data, hsfs_rw_info::data_len, hsfs_rw_info::data_val, DEBUG, DEBUG_IN, DEBUG_OUT, HSFS_FILE_SYNC, HSFS_UNSTABLE, hsi_nfs3_write(), hsx_fuse_iget(), hsfs_inode::ino, hsfs_rw_info::inode, min, hsfs_rw_info::ret_count, hsfs_rw_info::rw_off, hsfs_rw_info::rw_size, hsfs_rw_info::stable, and hsfs_super::wsize.
void hsx_fuse_unlink (fuse_req_t req, fuse_ino_t parent, const char * name)
Remove a file.
Valid replies: fuse_reply_err
Parameters
req[in] request handle
parent[in] inode number of the parent directory
name[in] to remove
Definition at line 6 of file hsx_fuse_unlink.c.
References DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_unlink(), and hsx_fuse_iget().
void hsx_fuse_rename (fuse_req_t req, fuse_ino_t parent, const char * name, fuse_ino_t newparent, const char * newname)
Rename a file.
Valid replies: fuse_reply_err
Parameters
req[in] request handle
parent[in] inode number of the old parent directory
name[in] old name
newparent[in] inode number of the new parent directory
newname[in] new name
Definition at line 6 of file hsx_fuse_rename.c.
References DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_rename(), and hsx_fuse_iget().
void hsx_fuse_readlink (fuse_req_t req, fuse_ino_t ino)
Read the content of the symlink.
Valid replies: fuse_reply_readlink fuse_reply_err
Parameters
req[in] request handle
ino[in] the inode number
Definition at line 11 of file hsx_fuse_readlink.c.
References DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_readlink(), hsx_fuse_iget(), and progname.
void hsx_fuse_symlink (fuse_req_t req, const char * link, fuse_ino_t parent, const char * name)
Create a symbolic link.
Valid replies: fuse_reply_entry fuse_reply_err
Parameters
req[in] request handle
link[in] the contents of the symbolic link
parent[in] inode number of the parent directory
name[in] to create
Definition at line 13 of file hsx_fuse_symlink.c.
References DEBUG, DEBUG_IN, ERR, hsi_nfs3_symlink(), hsx_fuse_fill_reply(), hsx_fuse_iget(), and progname.
void hsx_fuse_access (fuse_req_t req, fuse_ino_t ino, int mask)
Request permission to an operation.
Valid replies: fuse_reply_err
Parameters
req[in] request handle
ino[in] inode number to request
mask[in] request permission
Definition at line 10 of file hsx_fuse_access.c.
References ACCESS3_DELETE, ACCESS3_EXECUTE, ACCESS3_EXTEND, ACCESS3_LOOKUP, ACCESS3_MODIFY, ACCESS3_READ, hsfs_inode::attr, DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_access(), hsx_fuse_iget(), and fattr3::type.
void hsx_fuse_create (fuse_req_t req, fuse_ino_t parent, const char * name, mode_t mode, struct fuse_file_info * fi)
Create a regular file.
Valid replies: fuse_repay_create fuse_reply_err
Parameters
req[in] request handle
parent[in] the inode number of the parent directory
name[in] new file name
mode[in] access mode to the new file
fi[in] file information
Definition at line 7 of file hsx_fuse_create.c.
References hsfs_inode::attr, DEBUG_IN, DEBUG_OUT, ERR, fattr3::gid, hsi_nfs3_create(), hsx_fuse_fill_reply(), hsx_fuse_iget(), and fattr3::uid.
void hsx_fuse_mknod (fuse_req_t req, fuse_ino_t parent, const char * name, mode_t mode, dev_t rdev)
Create a special file.
Valid replies: fuse_reply_entry fuse_reply_err
Parameters
req[in] request handle
parent[in] the inode number of the parent directory
name[in] the name of the special file you want to create
mode[in] file type and access mode of the file
rdev[in] device number of the special file
Definition at line 7 of file hsx_fuse_mknod.c.
References DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_mknod(), hsx_fuse_fill_reply(), hsx_fuse_iget(), and progname.
void hsx_fuse_link (fuse_req_t req, fuse_ino_t ino, fuse_ino_t newparent, const char * newname)
Create a hard link to a file.
Valid replies: fuse_reply_entry fuse_reply_err
Parameters
req[in] request handle
ino[in] the old inode number
newparent[in] inode number of the new parent directory
newname[in] new name to create
Definition at line 7 of file hsx_fuse_link.c.
References DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_link(), hsx_fuse_fill_reply(), hsx_fuse_iget(), and progname.
void hsx_fuse_lookup (fuse_req_t req, fuse_ino_t ino, const char * name)
Look up a directory entry by name.
Valid replies: fuse_reply_entry fuse_reply_err
Parameters
req[in] request handle
ino[in] inode number of the parent directory
name[in] the name to look up
Definition at line 5 of file hsx_fuse_lookup.c.
References DEBUG_IN, DEBUG_OUT, hsi_nfs3_lookup(), hsx_fuse_fill_reply(), and hsx_fuse_iget().
void hsx_fuse_forget (fuse_req_t req, fuse_ino_t ino, unsigned long nlookup)
Forget about an inode.
Valid replies: fuse_reply_none
Parameters
req[in] request handle
ino[in] the inode number to forget
nlookup[in] the number of lookups to forget
Definition at line 4 of file hsx_fuse_forget.c.
References DEBUG, DEBUG_IN, DEBUG_OUT, ERR, hsx_fuse_idel(), hsx_fuse_iget(), and hsfs_inode::nlookup.
void hsx_fuse_open (fuse_req_t req, fuse_ino_t ino, struct fuse_file_info * fi)
Open a file.
replies: fuse_reply_err fuse_reply_open
Parameters
req[in] request handle
ino[in] the old inode number
fi[in] file information
Definition at line 11 of file hsx_fuse_open.c.
References DEBUG_IN, DEBUG_OUT, ERR, and FI_FH_LEN.
void hsx_fuse_release (fuse_req_t req, fuse_ino_t ino, struct fuse_file_info * fi)
Release a file.
replies: fuse_reply_err
Parameters
req[in] request handle
ino[in] the old inode number
fi[in] file information
hsx_fuse_release liuyoujin
Definition at line 10 of file hsx_fuse_release.c.
References DEBUG_IN, and DEBUG_OUT.
void hsx_fuse_getattr (fuse_req_t req, fuse_ino_t ino, struct fuse_file_info * fi)
Get file attributes.
Valid replies: fuse_reply_err, fuse_reply_attr
Parameters
req[in] request handle
ino[in] the inode number
fi[in] for future use, currently always NULL
Definition at line 4 of file hsx_fuse_getattr.c.
References hsfs_super::acdirmin, hsfs_super::acregmin, hsfs_inode::attr, DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_fattr2stat(), hsi_nfs3_getattr(), hsx_fuse_iget(), hsfs_inode::ino, NF3DIR, and fattr3::type.
void hsx_fuse_setattr (fuse_req_t req, fuse_ino_t ino, struct stat * attr, int to_set, struct fuse_file_info * fi)
Set file attributes
Valid replies: fuse_reply_err, fuse_reply_attr
Parameters
req[in] request handle
ino[in] the inode number
attr[in] the attributes
to_set[in] bit mask of attributes which should be set
fi[in] file information, or NULL
Definition at line 4 of file hsx_fuse_setattr.c.
References hsfs_super::acdirmin, hsfs_super::acregmin, hsfs_inode::attr, DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_fattr2stat(), hsi_nfs3_setattr(), hsi_nfs3_stat2sattr(), hsx_fuse_iget(), hsfs_inode::ino, NF3DIR, and fattr3::type.
void hsx_fuse_statfs (fuse_req_t req, fuse_ino_t ino)
Get the filesystem statistics.
Valid replies: fuse_reply_statfs fuse_reply_err
Parameters
req[in] request handle
ino[in] the inode number
Definition at line 5 of file hsx_fuse_statfs.c.
References DEBUG_IN, DEBUG_OUT, hsi_nfs3_statfs(), hsi_super2statvfs(), hsfs_super::root, and hsfs_inode::sb.
void hsx_fuse_readdir (fuse_req_t req, fuse_ino_t ino, size_t size, off_t off, struct fuse_file_info * fi)
Read the content of the directory.
Valid replies: fuse_reply_buf fuse_reply_err
Parameters
req[in] request handle
ino[in] the inode number
size[in] the maximum number of bytes to send
off[in] the offset to continue reading the directory
fi[in] the file information
Definition at line 9 of file hsx_fuse_readdir.c.
References DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_readdir(), hsx_fuse_iget(), min, hsfs_readdir_ctx::name, hsfs_readdir_ctx::next, hsfs_readdir_ctx::off, progname, RPCCOUNT, and hsfs_readdir_ctx::stbuf.
void hsx_fuse_opendir (fuse_req_t req, fuse_ino_t ino, struct fuse_file_info * fi)
Open a directory.
Valid replies: fuse_reply_open fuse_reply_err
Parameters
req[in] request handle
ino[in] the inode number
fi[in,out] the file information
Definition at line 9 of file hsx_fuse_opendir.c.
References DEBUG_IN, DEBUG_OUT, ERR, hsx_fuse_iget(), and progname.
struct fuse_chan* hsx_fuse_mount (const char * spec, const char * point, struct fuse_args * args, char * udata, struct hsfs_super * super) read
Mount NFS filesystem (get root filehandle)
Parameters
spec[in] mount spec at remote node
point[in] mount point at local node
args[out] save fuse arguments which is mapping from nfs
udata[out] nfs arguments which is used for mtab
super[out] hsfs super block
Returns
fuse channel
Definition at line 586 of file hsi_nfs3_mount.c.
References hsfs_super::acdirmax, hsfs_super::acdirmin, hsfs_super::acl_clntp, hsfs_super::acregmax, hsfs_super::acregmin, hsfs_super::addr, mountres3_ok::auth_flavors, mountres3_ok::auth_flavors_len, mountres3_ok::auth_flavors_val, hsfs_super::clntp, ERR, fg, clnt_addr_t::hostname, hsi_validate_mount_data(), INFO, NFS_ACL_PROGRAM, NFS_ACL_V3, clnt_addr_t::pmap, progname, hsfs_super::retrans, hsfs_super::rsize, clnt_addr_t::saddr, hsfs_super::timeo, verbose, and hsfs_super::wsize.
Referenced by main().
int hsx_fuse_unmount (const char * spec, const char * point, struct fuse_chan * ch, struct hsfs_super * super)
Unmount NFS filesystem (release root filehandle)
Parameters
spec[in] mount spec at remote node
point[in] mount point at local node
ch[in] fuse channel for hsfs
super[out] hsfs super block
Returns
errno number as Linux system
Definition at line 767 of file hsi_nfs3_mount.c.
References hsfs_super::addr, hsfs_super::clntp, hsfs_super::flags, clnt_addr_t::hostname, hsx_fuse_idel(), hsx_fuse_itable_del(), MOUNTPROG, MOUNTVERS_NFSV3, NFS_MOUNT_TCP, clnt_addr_t::pmap, hsfs_super::root, and clnt_addr_t::saddr.
Referenced by main().
void hsx_fuse_getxattr (fuse_req_t req, fuse_ino_t ino, const char * name, size_t size)
Get extended attribute.
Parameters
req[in] request handle
ino[in] the inode number
name[in] of the extended attribute
size[in] maximum size of the value to send
Definition at line 5 of file hsx_fuse_getxattr.c.
References ACL_TYPE_ACCESS, ACL_TYPE_DEFAULT, DEBUG_IN, DEBUG_OUT, hsi_nfs3_getxattr(), hsx_fuse_iget(), NA_ACL, NA_ACLCNT, NA_DFACL, NA_DFACLCNT, posix_acl_to_xattr(), POSIX_ACL_XATTR_ACCESS, and POSIX_ACL_XATTR_DEFAULT.
void hsx_fuse_setxattr (fuse_req_t req, fuse_ino_t ino, const char * name, const char * value, size_t size, int flags)
Set extended attribute.
Valid replies: fuse_reply_err
Parameters
req[in] file requset handle
ino[in] inode number
name[in] the mask of operation
value[in] data of the extended attributes
size[in] the data size
flags[in] extended arg
Definition at line 6 of file hsx_fuse_setxattr.c.
References ACL_TYPE_ACCESS, ACL_TYPE_DEFAULT, DEBUG_IN, DEBUG_OUT, ERR, hsi_nfs3_setxattr(), hsx_fuse_iget(), POSIX_ACL_XATTR_ACCESS, and POSIX_ACL_XATTR_DEFAULT.