hsfs: /hsfs/include/mount.h File Reference
mount.h File Reference
#include <rpc/rpc.h>
#include <memory.h>
Data Structures
struct fhstatus
struct mountbody
struct groupnode
struct exportnode
struct ppathcnf
struct fhandle3
struct mountres3_ok
struct mountres3
Macros
#define _rpcsvc_mount_h
#define MNTPATHLEN 1024
#define MNTNAMLEN 255
#define FHSIZE 32
#define FHSIZE3 64
#define MOUNTPROG 100005
#define MOUNTVERS 1
#define MOUNTPROC_NULL 0
#define MOUNTPROC_MNT 1
#define MOUNTPROC_DUMP 2
#define MOUNTPROC_UMNT 3
#define MOUNTPROC_UMNTALL 4
#define MOUNTPROC_EXPORT 5
#define MOUNTPROC_EXPORTALL 6
#define MOUNTVERS_POSIX 2
#define MOUNTPROC_PATHCONF 7
#define MOUNTVERS_NFSV3 3
#define MOUNTPROC3_NULL 0
#define MOUNTPROC3_MNT 1
#define MOUNTPROC3_DUMP 2
#define MOUNTPROC3_UMNT 3
#define MOUNTPROC3_UMNTALL 4
#define MOUNTPROC3_EXPORT 5
Typedefs
typedef char fhandle [FHSIZE]
typedef struct fhstatus fhstatus
typedef char * dirpath
typedef char * name
typedef struct mountbody * mountlist
typedef struct mountbody mountbody
typedef struct groupnode * groups
typedef struct groupnode groupnode
typedef struct exportnode * exports
typedef struct exportnode exportnode
typedef struct ppathcnf ppathcnf
typedef enum mountstat3 mountstat3
typedef struct mountres3_ok mountres3_ok
typedef struct mountres3 mountres3
Enumerations
enum mountstat3 {
MNT_OK = 0, MNT3ERR_PERM = 1, MNT3ERR_NOENT = 2, MNT3ERR_IO = 5,
MNT3ERR_ACCES = 13, MNT3ERR_NOTDIR = 20, MNT3ERR_INVAL = 22, MNT3ERR_NAMETOOLONG = 63,
MNT3ERR_NOTSUPP = 10004, MNT3ERR_SERVERFAULT = 10006
}
Functions
void * mountproc_null_1 ()
void * mountproc_null_1_svc ()
fhstatus * mountproc_mnt_1 ()
fhstatus * mountproc_mnt_1_svc ()
mountlist * mountproc_dump_1 ()
mountlist * mountproc_dump_1_svc ()
void * mountproc_umnt_1 ()
void * mountproc_umnt_1_svc ()
void * mountproc_umntall_1 ()
void * mountproc_umntall_1_svc ()
exports * mountproc_export_1 ()
exports * mountproc_export_1_svc ()
exports * mountproc_exportall_1 ()
exports * mountproc_exportall_1_svc ()
int mountprog_1_freeresult ()
void * mountproc_null_2 ()
void * mountproc_null_2_svc ()
fhstatus * mountproc_mnt_2 ()
fhstatus * mountproc_mnt_2_svc ()
mountlist * mountproc_dump_2 ()
mountlist * mountproc_dump_2_svc ()
void * mountproc_umnt_2 ()
void * mountproc_umnt_2_svc ()
void * mountproc_umntall_2 ()
void * mountproc_umntall_2_svc ()
exports * mountproc_export_2 ()
exports * mountproc_export_2_svc ()
exports * mountproc_exportall_2 ()
exports * mountproc_exportall_2_svc ()
ppathcnf * mountproc_pathconf_2 ()
ppathcnf * mountproc_pathconf_2_svc ()
int mountprog_2_freeresult ()
void * mountproc3_null_3 ()
void * mountproc3_null_3_svc ()
mountres3 * mountproc3_mnt_3 ()
mountres3 * mountproc3_mnt_3_svc ()
mountlist * mountproc3_dump_3 ()
mountlist * mountproc3_dump_3_svc ()
void * mountproc3_umnt_3 ()
void * mountproc3_umnt_3_svc ()
void * mountproc3_umntall_3 ()
void * mountproc3_umntall_3_svc ()
exports * mountproc3_export_3 ()
exports * mountproc3_export_3_svc ()
int mountprog_3_freeresult ()
bool_t xdr_fhandle ()
bool_t xdr_fhstatus ()
bool_t xdr_dirpath ()
bool_t xdr_name ()
bool_t xdr_mountlist ()
bool_t xdr_mountbody ()
bool_t xdr_groups ()
bool_t xdr_groupnode ()
bool_t xdr_exports ()
bool_t xdr_exportnode ()
bool_t xdr_ppathcnf ()
bool_t xdr_fhandle3 ()
bool_t xdr_mountstat3 ()
bool_t xdr_mountres3_ok ()
bool_t xdr_mountres3 ()
Macro Definition Documentation
#define _rpcsvc_mount_h
Definition at line 51 of file mount.h.
#define MNTPATHLEN 1024
Definition at line 53 of file mount.h.
Referenced by xdr_dirpath().
#define MNTNAMLEN 255
Definition at line 54 of file mount.h.
Referenced by xdr_name().
#define FHSIZE 32
Definition at line 55 of file mount.h.
Referenced by xdr_fhandle().
#define FHSIZE3 64
Definition at line 109 of file mount.h.
Referenced by xdr_fhandle3().
#define MOUNTPROG 100005
_rpcsvc_mount_h
Definition at line 148 of file mount.h.
Referenced by hsi_validate_mount_data(), and hsx_fuse_unmount().
#define MOUNTVERS 1
Definition at line 149 of file mount.h.
#define MOUNTPROC_NULL 0
Definition at line 176 of file mount.h.
Referenced by mountproc_null_1(), and mountproc_null_2().
#define MOUNTPROC_MNT 1
Definition at line 179 of file mount.h.
Referenced by mountproc_mnt_1(), and mountproc_mnt_2().
#define MOUNTPROC_DUMP 2
Definition at line 182 of file mount.h.
Referenced by mountproc_dump_1(), and mountproc_dump_2().
#define MOUNTPROC_UMNT 3
Definition at line 185 of file mount.h.
Referenced by mountproc_umnt_1(), and mountproc_umnt_2().
#define MOUNTPROC_UMNTALL 4
Definition at line 188 of file mount.h.
Referenced by mountproc_umntall_1(), and mountproc_umntall_2().
#define MOUNTPROC_EXPORT 5
Definition at line 191 of file mount.h.
Referenced by mountproc_export_1(), and mountproc_export_2().
#define MOUNTPROC_EXPORTALL 6
Definition at line 194 of file mount.h.
Referenced by mountproc_exportall_1(), and mountproc_exportall_2().
#define MOUNTVERS_POSIX 2
Definition at line 199 of file mount.h.
#define MOUNTPROC_PATHCONF 7
Definition at line 236 of file mount.h.
Referenced by mountproc_pathconf_2().
#define MOUNTVERS_NFSV3 3
Definition at line 241 of file mount.h.
Referenced by hsi_validate_mount_data(), and hsx_fuse_unmount().
#define MOUNTPROC3_NULL 0
Definition at line 265 of file mount.h.
Referenced by mountproc3_null_3().
#define MOUNTPROC3_MNT 1
Definition at line 268 of file mount.h.
Referenced by mountproc3_mnt_3().
#define MOUNTPROC3_DUMP 2
Definition at line 271 of file mount.h.
Referenced by mountproc3_dump_3().
#define MOUNTPROC3_UMNT 3
Definition at line 274 of file mount.h.
Referenced by mountproc3_umnt_3().
#define MOUNTPROC3_UMNTALL 4
Definition at line 277 of file mount.h.
Referenced by mountproc3_umntall_3().
#define MOUNTPROC3_EXPORT 5
Definition at line 280 of file mount.h.
Referenced by mountproc3_export_3().
Typedef Documentation
typedef char fhandle[FHSIZE]
Definition at line 57 of file mount.h.
typedef struct fhstatus fhstatus
Definition at line 65 of file mount.h.
typedef char* dirpath
Definition at line 67 of file mount.h.
typedef char* name
Definition at line 69 of file mount.h.
typedef struct mountbody* mountlist
Definition at line 71 of file mount.h.
typedef struct mountbody mountbody
Definition at line 78 of file mount.h.
typedef struct groupnode* groups
Definition at line 80 of file mount.h.
typedef struct groupnode groupnode
Definition at line 86 of file mount.h.
typedef struct exportnode* exports
Definition at line 88 of file mount.h.
typedef struct exportnode exportnode
Definition at line 95 of file mount.h.
typedef struct ppathcnf ppathcnf
Definition at line 108 of file mount.h.
typedef enum mountstat3 mountstat3
Definition at line 128 of file mount.h.
typedef struct mountres3_ok mountres3_ok
Definition at line 137 of file mount.h.
typedef struct mountres3 mountres3
Definition at line 145 of file mount.h.
Enumeration Type Documentation
enum mountstat3
Enumerator:
MNT_OK
MNT3ERR_PERM
MNT3ERR_NOENT
MNT3ERR_IO
MNT3ERR_ACCES
MNT3ERR_NOTDIR
MNT3ERR_INVAL
MNT3ERR_NAMETOOLONG
MNT3ERR_NOTSUPP
MNT3ERR_SERVERFAULT
Definition at line 116 of file mount.h.
Function Documentation
void* mountproc_null_1 ()
void* mountproc_null_1_svc ()
fhstatus* mountproc_mnt_1 ()
fhstatus* mountproc_mnt_1_svc ()
mountlist* mountproc_dump_1 ()
mountlist* mountproc_dump_1_svc ()
void* mountproc_umnt_1 ()
void* mountproc_umnt_1_svc ()
void* mountproc_umntall_1 ()
void* mountproc_umntall_1_svc ()
exports* mountproc_export_1 ()
exports* mountproc_export_1_svc ()
exports* mountproc_exportall_1 ()
exports* mountproc_exportall_1_svc ()
int mountprog_1_freeresult ()
void* mountproc_null_2 ()
void* mountproc_null_2_svc ()
fhstatus* mountproc_mnt_2 ()
fhstatus* mountproc_mnt_2_svc ()
mountlist* mountproc_dump_2 ()
mountlist* mountproc_dump_2_svc ()
void* mountproc_umnt_2 ()
void* mountproc_umnt_2_svc ()
void* mountproc_umntall_2 ()
void* mountproc_umntall_2_svc ()
exports* mountproc_export_2 ()
exports* mountproc_export_2_svc ()
exports* mountproc_exportall_2 ()
exports* mountproc_exportall_2_svc ()
ppathcnf* mountproc_pathconf_2 ()
ppathcnf* mountproc_pathconf_2_svc ()
int mountprog_2_freeresult ()
void* mountproc3_null_3 ()
void* mountproc3_null_3_svc ()
mountres3* mountproc3_mnt_3 ()
mountres3* mountproc3_mnt_3_svc ()
mountlist* mountproc3_dump_3 ()
mountlist* mountproc3_dump_3_svc ()
void* mountproc3_umnt_3 ()
void* mountproc3_umnt_3_svc ()
void* mountproc3_umntall_3 ()
void* mountproc3_umntall_3_svc ()
exports* mountproc3_export_3 ()
exports* mountproc3_export_3_svc ()
int mountprog_3_freeresult ()
bool_t xdr_fhandle ()
Referenced by xdr_fhstatus().
bool_t xdr_fhstatus ()
Referenced by mountproc_mnt_1(), and mountproc_mnt_2().
bool_t xdr_dirpath ()
Referenced by mountproc3_mnt_3(), mountproc3_umnt_3(), mountproc_mnt_1(), mountproc_mnt_2(), mountproc_pathconf_2(), mountproc_umnt_1(), mountproc_umnt_2(), xdr_exportnode(), and xdr_mountbody().
bool_t xdr_name ()
Referenced by xdr_groupnode(), and xdr_mountbody().
bool_t xdr_mountlist ()
Referenced by mountproc3_dump_3(), mountproc_dump_1(), mountproc_dump_2(), and xdr_mountbody().
bool_t xdr_mountbody ()
Referenced by xdr_mountlist().
bool_t xdr_groups ()
Referenced by xdr_exportnode(), and xdr_groupnode().
bool_t xdr_groupnode ()
Referenced by xdr_groups().
bool_t xdr_exports ()
Referenced by mountproc3_export_3(), mountproc_export_1(), mountproc_export_2(), mountproc_exportall_1(), mountproc_exportall_2(), and xdr_exportnode().
bool_t xdr_exportnode ()
Referenced by xdr_exports().
bool_t xdr_ppathcnf ()
Referenced by mountproc_pathconf_2().
bool_t xdr_fhandle3 ()
Referenced by xdr_mountres3_ok().
bool_t xdr_mountstat3 ()
Referenced by xdr_mountres3().
bool_t xdr_mountres3_ok ()
Referenced by xdr_mountres3().
bool_t xdr_mountres3 ()
Referenced by mountproc3_mnt_3().