hsfs: /hsfs/nfs3/mount_clnt.c File Reference
mount_clnt.c File Reference
#include <memory.h>
#include "mount.h"
Functions
void * mountproc_null_1 (void *argp, CLIENT *clnt)
fhstatus * mountproc_mnt_1 (dirpath *argp, CLIENT *clnt)
mountlist * mountproc_dump_1 (void *argp, CLIENT *clnt)
void * mountproc_umnt_1 (dirpath *argp, CLIENT *clnt)
void * mountproc_umntall_1 (void *argp, CLIENT *clnt)
exports * mountproc_export_1 (void *argp, CLIENT *clnt)
exports * mountproc_exportall_1 (void *argp, CLIENT *clnt)
void * mountproc_null_2 (void *argp, CLIENT *clnt)
fhstatus * mountproc_mnt_2 (dirpath *argp, CLIENT *clnt)
mountlist * mountproc_dump_2 (void *argp, CLIENT *clnt)
void * mountproc_umnt_2 (dirpath *argp, CLIENT *clnt)
void * mountproc_umntall_2 (void *argp, CLIENT *clnt)
exports * mountproc_export_2 (void *argp, CLIENT *clnt)
exports * mountproc_exportall_2 (void *argp, CLIENT *clnt)
ppathcnf * mountproc_pathconf_2 (dirpath *argp, CLIENT *clnt)
void * mountproc3_null_3 (void *argp, CLIENT *clnt)
mountres3 * mountproc3_mnt_3 (dirpath *argp, CLIENT *clnt)
mountlist * mountproc3_dump_3 (void *argp, CLIENT *clnt)
void * mountproc3_umnt_3 (dirpath *argp, CLIENT *clnt)
void * mountproc3_umntall_3 (void *argp, CLIENT *clnt)
exports * mountproc3_export_3 (void *argp, CLIENT *clnt)
Function Documentation
void* mountproc_null_1 (void * argp, CLIENT * clnt)
Definition at line 47 of file mount_clnt.c.
References MOUNTPROC_NULL.
fhstatus* mountproc_mnt_1 (dirpath * argp, CLIENT * clnt)
Definition at line 62 of file mount_clnt.c.
References MOUNTPROC_MNT, xdr_dirpath(), and xdr_fhstatus().
mountlist* mountproc_dump_1 (void * argp, CLIENT * clnt)
Definition at line 77 of file mount_clnt.c.
References MOUNTPROC_DUMP, and xdr_mountlist().
void* mountproc_umnt_1 (dirpath * argp, CLIENT * clnt)
Definition at line 92 of file mount_clnt.c.
References MOUNTPROC_UMNT, and xdr_dirpath().
void* mountproc_umntall_1 (void * argp, CLIENT * clnt)
Definition at line 107 of file mount_clnt.c.
References MOUNTPROC_UMNTALL.
exports* mountproc_export_1 (void * argp, CLIENT * clnt)
Definition at line 122 of file mount_clnt.c.
References MOUNTPROC_EXPORT, and xdr_exports().
exports* mountproc_exportall_1 (void * argp, CLIENT * clnt)
Definition at line 137 of file mount_clnt.c.
References MOUNTPROC_EXPORTALL, and xdr_exports().
void* mountproc_null_2 (void * argp, CLIENT * clnt)
Definition at line 152 of file mount_clnt.c.
References MOUNTPROC_NULL.
fhstatus* mountproc_mnt_2 (dirpath * argp, CLIENT * clnt)
Definition at line 167 of file mount_clnt.c.
References MOUNTPROC_MNT, xdr_dirpath(), and xdr_fhstatus().
mountlist* mountproc_dump_2 (void * argp, CLIENT * clnt)
Definition at line 182 of file mount_clnt.c.
References MOUNTPROC_DUMP, and xdr_mountlist().
void* mountproc_umnt_2 (dirpath * argp, CLIENT * clnt)
Definition at line 197 of file mount_clnt.c.
References MOUNTPROC_UMNT, and xdr_dirpath().
void* mountproc_umntall_2 (void * argp, CLIENT * clnt)
Definition at line 212 of file mount_clnt.c.
References MOUNTPROC_UMNTALL.
exports* mountproc_export_2 (void * argp, CLIENT * clnt)
Definition at line 227 of file mount_clnt.c.
References MOUNTPROC_EXPORT, and xdr_exports().
exports* mountproc_exportall_2 (void * argp, CLIENT * clnt)
Definition at line 242 of file mount_clnt.c.
References MOUNTPROC_EXPORTALL, and xdr_exports().
ppathcnf* mountproc_pathconf_2 (dirpath * argp, CLIENT * clnt)
Definition at line 257 of file mount_clnt.c.
References MOUNTPROC_PATHCONF, xdr_dirpath(), and xdr_ppathcnf().
void* mountproc3_null_3 (void * argp, CLIENT * clnt)
Definition at line 272 of file mount_clnt.c.
References MOUNTPROC3_NULL.
mountres3* mountproc3_mnt_3 (dirpath * argp, CLIENT * clnt)
Definition at line 287 of file mount_clnt.c.
References MOUNTPROC3_MNT, xdr_dirpath(), and xdr_mountres3().
mountlist* mountproc3_dump_3 (void * argp, CLIENT * clnt)
Definition at line 302 of file mount_clnt.c.
References MOUNTPROC3_DUMP, and xdr_mountlist().
void* mountproc3_umnt_3 (dirpath * argp, CLIENT * clnt)
Definition at line 317 of file mount_clnt.c.
References MOUNTPROC3_UMNT, and xdr_dirpath().
void* mountproc3_umntall_3 (void * argp, CLIENT * clnt)
Definition at line 332 of file mount_clnt.c.
References MOUNTPROC3_UMNTALL.
exports* mountproc3_export_3 (void * argp, CLIENT * clnt)
Definition at line 347 of file mount_clnt.c.
References MOUNTPROC3_EXPORT, and xdr_exports().