hsfs: /hsfs/nfs3/nfs3clnt.c File Reference
nfs3clnt.c File Reference
#include <memory.h>
#include "nfs3.h"
Functions
void * nfsproc3_null_3 (void *argp, CLIENT *clnt)
getattr3res * nfsproc3_getattr_3 (nfs_fh3 *argp, CLIENT *clnt)
wccstat3 * nfsproc3_setattr_3 (setattr3args *argp, CLIENT *clnt)
lookup3res * nfsproc3_lookup_3 (diropargs3 *argp, CLIENT *clnt)
access3res * nfsproc3_access_3 (access3args *argp, CLIENT *clnt)
readlink3res * nfsproc3_readlink_3 (nfs_fh3 *argp, CLIENT *clnt)
read3res * nfsproc3_read_3 (read3args *argp, CLIENT *clnt)
write3res * nfsproc3_write_3 (write3args *argp, CLIENT *clnt)
diropres3 * nfsproc3_create_3 (create3args *argp, CLIENT *clnt)
diropres3 * nfsproc3_mkdir_3 (mkdir3args *argp, CLIENT *clnt)
diropres3 * nfsproc3_symlink_3 (symlink3args *argp, CLIENT *clnt)
diropres3 * nfsproc3_mknod_3 (mknod3args *argp, CLIENT *clnt)
wccstat3 * nfsproc3_remove_3 (diropargs3 *argp, CLIENT *clnt)
wccstat3 * nfsproc3_rmdir_3 (diropargs3 *argp, CLIENT *clnt)
rename3res * nfsproc3_rename_3 (rename3args *argp, CLIENT *clnt)
link3res * nfsproc3_link_3 (link3args *argp, CLIENT *clnt)
readdir3res * nfsproc3_readdir_3 (readdir3args *argp, CLIENT *clnt)
readdirplus3res * nfsproc3_readdirplus_3 (readdirplus3args *argp, CLIENT *clnt)
fsstat3res * nfsproc3_fsstat_3 (nfs_fh3 *argp, CLIENT *clnt)
fsinfo3res * nfsproc3_fsinfo_3 (nfs_fh3 *argp, CLIENT *clnt)
pathconf3res * nfsproc3_pathconf_3 (nfs_fh3 *argp, CLIENT *clnt)
commit3res * nfsproc3_commit_3 (commit3args *argp, CLIENT *clnt)
Function Documentation
void* nfsproc3_null_3 (void * argp, CLIENT * clnt)
Definition at line 13 of file nfs3clnt.c.
References NFSPROC3_NULL.
getattr3res* nfsproc3_getattr_3 (nfs_fh3 * argp, CLIENT * clnt)
Definition at line 28 of file nfs3clnt.c.
References NFSPROC3_GETATTR, xdr_getattr3res(), and xdr_nfs_fh3().
wccstat3* nfsproc3_setattr_3 (setattr3args * argp, CLIENT * clnt)
Definition at line 43 of file nfs3clnt.c.
References NFSPROC3_SETATTR, xdr_setattr3args(), and xdr_wccstat3().
lookup3res* nfsproc3_lookup_3 (diropargs3 * argp, CLIENT * clnt)
Definition at line 58 of file nfs3clnt.c.
References NFSPROC3_LOOKUP, xdr_diropargs3(), and xdr_lookup3res().
access3res* nfsproc3_access_3 (access3args * argp, CLIENT * clnt)
Definition at line 73 of file nfs3clnt.c.
References NFSPROC3_ACCESS, xdr_access3args(), and xdr_access3res().
readlink3res* nfsproc3_readlink_3 (nfs_fh3 * argp, CLIENT * clnt)
Definition at line 88 of file nfs3clnt.c.
References NFSPROC3_READLINK, xdr_nfs_fh3(), and xdr_readlink3res().
read3res* nfsproc3_read_3 (read3args * argp, CLIENT * clnt)
Definition at line 103 of file nfs3clnt.c.
References NFSPROC3_READ, xdr_read3args(), and xdr_read3res().
write3res* nfsproc3_write_3 (write3args * argp, CLIENT * clnt)
Definition at line 118 of file nfs3clnt.c.
References NFSPROC3_WRITE, xdr_write3args(), and xdr_write3res().
diropres3* nfsproc3_create_3 (create3args * argp, CLIENT * clnt)
Definition at line 133 of file nfs3clnt.c.
References NFSPROC3_CREATE, xdr_create3args(), and xdr_diropres3().
diropres3* nfsproc3_mkdir_3 (mkdir3args * argp, CLIENT * clnt)
Definition at line 148 of file nfs3clnt.c.
References NFSPROC3_MKDIR, xdr_diropres3(), and xdr_mkdir3args().
diropres3* nfsproc3_symlink_3 (symlink3args * argp, CLIENT * clnt)
Definition at line 163 of file nfs3clnt.c.
References NFSPROC3_SYMLINK, xdr_diropres3(), and xdr_symlink3args().
diropres3* nfsproc3_mknod_3 (mknod3args * argp, CLIENT * clnt)
Definition at line 178 of file nfs3clnt.c.
References NFSPROC3_MKNOD, xdr_diropres3(), and xdr_mknod3args().
wccstat3* nfsproc3_remove_3 (diropargs3 * argp, CLIENT * clnt)
Definition at line 193 of file nfs3clnt.c.
References NFSPROC3_REMOVE, xdr_diropargs3(), and xdr_wccstat3().
wccstat3* nfsproc3_rmdir_3 (diropargs3 * argp, CLIENT * clnt)
Definition at line 208 of file nfs3clnt.c.
References NFSPROC3_RMDIR, xdr_diropargs3(), and xdr_wccstat3().
rename3res* nfsproc3_rename_3 (rename3args * argp, CLIENT * clnt)
Definition at line 223 of file nfs3clnt.c.
References NFSPROC3_RENAME, xdr_rename3args(), and xdr_rename3res().
link3res* nfsproc3_link_3 (link3args * argp, CLIENT * clnt)
Definition at line 238 of file nfs3clnt.c.
References NFSPROC3_LINK, xdr_link3args(), and xdr_link3res().
readdir3res* nfsproc3_readdir_3 (readdir3args * argp, CLIENT * clnt)
Definition at line 253 of file nfs3clnt.c.
References NFSPROC3_READDIR, xdr_readdir3args(), and xdr_readdir3res().
readdirplus3res* nfsproc3_readdirplus_3 (readdirplus3args * argp, CLIENT * clnt)
Definition at line 268 of file nfs3clnt.c.
References NFSPROC3_READDIRPLUS, xdr_readdirplus3args(), and xdr_readdirplus3res().
fsstat3res* nfsproc3_fsstat_3 (nfs_fh3 * argp, CLIENT * clnt)
Definition at line 283 of file nfs3clnt.c.
References NFSPROC3_FSSTAT, xdr_fsstat3res(), and xdr_nfs_fh3().
fsinfo3res* nfsproc3_fsinfo_3 (nfs_fh3 * argp, CLIENT * clnt)
Definition at line 298 of file nfs3clnt.c.
References NFSPROC3_FSINFO, xdr_fsinfo3res(), and xdr_nfs_fh3().
pathconf3res* nfsproc3_pathconf_3 (nfs_fh3 * argp, CLIENT * clnt)
Definition at line 313 of file nfs3clnt.c.
References NFSPROC3_PATHCONF, xdr_nfs_fh3(), and xdr_pathconf3res().
commit3res* nfsproc3_commit_3 (commit3args * argp, CLIENT * clnt)
Definition at line 328 of file nfs3clnt.c.
References NFSPROC3_COMMIT, xdr_commit3args(), and xdr_commit3res().