hsfs: /hsfs/nfs3/nfs_mntent.c File Reference
nfs_mntent.c File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <sys/stat.h>
#include "nfs_mntent.h"
#include "nls.h"
#include "xcommon.h"
Macros
#define isoctal(a) (((a) & ~7) == '0')
Functions
mntFILE * nfs_setmntent (const char *file, char *mode)
void nfs_endmntent (mntFILE *mfp)
int nfs_addmntent (mntFILE *mfp, nfs_mntent_t *mnt)
nfs_mntent_t * nfs_getmntent (mntFILE *mfp)
Macro Definition Documentation
#define isoctal (a) (((a) & ~7) == '0')
Definition at line 73 of file nfs_mntent.c.
Function Documentation
mntFILE* nfs_setmntent (const char * file, char * mode)
Definition at line 102 of file nfs_mntent.c.
References mntFILEstruct::mntent_errs, mntFILEstruct::mntent_file, mntFILEstruct::mntent_fp, mntFILEstruct::mntent_lineno, mntFILEstruct::mntent_softerrs, xmalloc(), and xstrdup().
Referenced by read_fstab(), and update_mtab().
void nfs_endmntent (mntFILE * mfp)
Definition at line 116 of file nfs_mntent.c.
References mntFILEstruct::mntent_file, and mntFILEstruct::mntent_fp.
Referenced by update_mtab().
int nfs_addmntent (mntFILE * mfp, nfs_mntent_t * mnt)
Definition at line 127 of file nfs_mntent.c.
References nfs_mntent_s::mnt_dir, nfs_mntent_s::mnt_freq, nfs_mntent_s::mnt_fsname, nfs_mntent_s::mnt_opts, nfs_mntent_s::mnt_passno, nfs_mntent_s::mnt_type, and mntFILEstruct::mntent_fp.
Referenced by update_mtab().
nfs_mntent_t* nfs_getmntent (mntFILE * mfp)
Definition at line 151 of file nfs_mntent.c.
References _, ERR_MAX, nfs_mntent_s::mnt_dir, nfs_mntent_s::mnt_freq, nfs_mntent_s::mnt_fsname, nfs_mntent_s::mnt_opts, nfs_mntent_s::mnt_passno, nfs_mntent_s::mnt_type, mntFILEstruct::mntent_errs, mntFILEstruct::mntent_file, mntFILEstruct::mntent_fp, mntFILEstruct::mntent_lineno, and mntFILEstruct::mntent_softerrs.