hsfs: /hsfs/fuse/xcommon.c File Reference
xcommon.c File Reference
#include <unistd.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "xcommon.h"
#include "nls.h"
Functions
char * xstrndup (const char *s, int n)
char * xstrconcat2 (const char *s, const char *t)
char * xstrconcat3 (const char *s, const char *t, const char *u)
char * xstrconcat4 (const char *s, const char *t, const char *u, const char *v)
void nfs_error (const char *fmt,...)
char * canonicalize (const char *path)
void die (int err, const char *fmt,...)
void * xmalloc (size_t size)
void * xrealloc (void *p, size_t size)
void xfree (void *ptr)
char * xstrdup (const char *s)
Variables
void(* at_die)(void) = NULL
Function Documentation
char* xstrndup (const char * s, int n)
Definition at line 26 of file xcommon.c.
References _, die(), EX_SOFTWARE, and xmalloc().
char* xstrconcat2 (const char * s, const char * t)
Definition at line 40 of file xcommon.c.
References xmalloc().
Referenced by nfs_error().
char* xstrconcat3 (const char * s, const char * t, const char * u)
Definition at line 53 of file xcommon.c.
References xmalloc().
char* xstrconcat4 (const char * s, const char * t, const char * u, const char * v)
Definition at line 69 of file xcommon.c.
References xmalloc().
void nfs_error (const char * fmt, ...)
Definition at line 89 of file xcommon.c.
References xstrconcat2().
Referenced by read_fstab(), and update_mtab().
char* canonicalize (const char * path)
Definition at line 105 of file xcommon.c.
References streq, and xstrdup().
void die (int err, const char * fmt, ...)
Definition at line 125 of file xcommon.c.
References at_die.
Referenced by lock_mtab(), update_mtab(), and xstrndup().
void* xmalloc (size_t size)
Definition at line 146 of file xcommon.c.
Referenced by nfs_setmntent(), update_mtab(), xstrconcat2(), xstrconcat3(), xstrconcat4(), and xstrndup().
void* xrealloc (void * p, size_t size)
Definition at line 159 of file xcommon.c.
void xfree (void * ptr)
Definition at line 169 of file xcommon.c.
char* xstrdup (const char * s)
Definition at line 175 of file xcommon.c.
Referenced by canonicalize(), and nfs_setmntent().
Variable Documentation
void(* at_die)(void) = NULL
Definition at line 23 of file xcommon.c.
Referenced by die(), and lock_mtab().